package com.android.tomboati.view.activity.doa_dzikir;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import com.android.tomboati.R;
import com.android.tomboati.adapter.DoaHajiUmrahAdapter;
import com.android.tomboati.model.DoaHajiUmrahModel;

import java.util.ArrayList;
import java.util.List;

public class DoaUmrahActivity extends AppCompatActivity {

    private RecyclerView recyclerViewDoaUmrah;
    private DoaHajiUmrahAdapter doaHajiUmrahAdapter;
    private List<DoaHajiUmrahModel> models;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTheme(R.style.ThemeTomboAtiGreen);
        setContentView(R.layout.activity_doa_umrah);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        setTitle("Doa Umrah");
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);

        models = new ArrayList<>();

        recyclerViewDoaUmrah = findViewById(R.id.recyclerViewDoaUmrah);
        recyclerViewDoaUmrah.setHasFixedSize(true);
        recyclerViewDoaUmrah.setLayoutManager(new LinearLayoutManager(this));

        addItem("Doa Niat Umrah", "نَوَيْتُ العُمْرَةَ وَأَحْرَمْتُ بِهَا لِلهِ تَعَالَى لَبَّيْكَ اللَّهُمَّ بعُمْرَ", "Nawaitul ‘umrata wa ahramtu bihi lillahi ta’ala labbaika Allahumma umratan.", "Aku niat melaksanakan umrah dan berihram karena Allah SWT. Aku sambut panggilan-Mu, ya Allah untuk berumrah.", "Hal pertama yang harus diucapkan dalam melaksanakan rukun umrah adalah doa niat umrah.");
        addItem("Doa Miqat di Masjid Dzulhulaifah", "لَبَّيْكَ اللَّهُمَّ بِعُمْرَةِ", "Labbaika Allahumma bi 'Umrah.", "Aku sambut panggilanMu ya Allah dengan umrah.", "Miqat terletak di Madinah tempat jamaah melakukan persiapan sebelum ihram. Persiapan meliputi mandi, mengenakan pakaian ihram, berwudhu dan mengerjakan sholat sunnah ihram 2 rakaat. Setelah itu niat mengerjakan ibadah umroh dengan membaca bacaan niat umroh.");
        addItem("Doa Bacaan Talbiyah", "لَبَّیكَ الّلهُمَّ لَبَّیكَ، لَبَّیكَ لاشَریكَ لَكَ لَبَّیكَ، إنَّ الْحَمدَ وَ النِّعمَةَ لَكَ وَ الْمُلكَ، لاشَریكَ لَكَ لَبَّیكَ", "Labbaik Allahumma labbaik, labbaika laa syariika laka labbaik, innal hamda wan ni'mata laka wal mulk laa syariika laka labbaik.", "Aku penuhi panggilanMu ya Allah, aku penuhi panggilanMu ya Allah dan tiada sekutu bagiMu. Sesungguhnya segala puji, nikmat, serta kekuasaaan hanya bagi-Mu tanpa sekutu apapun bagi-Mu.", "Dalam perjalanan menuju Masjidil Haram dari miqat sebaiknya memperbanyak bacaan talbiyah yang diucapkan Rasulullah SAW ketika umroh dan haji.");
        addItem("Doa Sapu Jagad", "رَبَّنَا آتِنَا فِى الدُّنْيَا حَسَنَةً وَفِى الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "Rabbana Atina Fiddunya Hasanatan Wa Fil Akhirati Hasanata Wa Qina 'Adzabanar.", "Ya Tuhan kami, berilah kami kebaikan di dunia dan kebaikan di akhirat, dan peliharalah kami dari siksa api neraka.", "Sepanjang thawaf, membaca doa saat berada di antara Rukun Yamani dan Hajar Aswad. Doa saat thawaf yang selalu dibaca oleh Rasulullah SAW adalah doa sapu jagad.");
        addItem("Doa Masuk Masjidil Haram", "اَللّٰهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ فَحَيِّنَا رَبَّنَا بِالسَّلَامِ وَأَدْخِلْنَا الْجَنَّةَ دَارَالسَّلَامَ تَبَارَكْتَ وَتَعَالَيْتَ يَا ذَاالْجَلَالِ وَاْلإِكْرَامِ. اَللّٰهُمَّ افْتَحْ لِيْ أَبْوَابَ رَحْمَتِكَ وَمَغْفِرَتِكَ وَأَدْخِلْنِيْ فِيْهَا. بِسْمِ اللهِ وَالْحَمْدُ ِللهِ وَالصَّلَاةُ وَالسَّلَامُ عَلٰى رَسُوْلِ اللهِ.", "Allahumma antassalaam, waminkassalaam fahayyinaa rabbanaa bissalaam wa adkhilnal jannata daarassalaam tabaarakta wata'aalaita yaa dzaljalaali wal ikraam. Allahummaftah lii abwaaba rahmatika wamaghfiratika wa adkhilnii fiihaa. Bismillahi walhamdulillahi wasshalaatu wassalaamu 'alaa rasuulillaah.", "Ya Allah Engkau sumber keselamatan, dan daripadaMu lah datangnya keselamatan itu semua. Maka sambutlah kami wahai tuhan dengan selamat sejahtera dan masukanlah kami ke dalam surga negeriMu yang bahagia, Maha Pemberi berkat dan Maha Tinggilah Engkau wahai Tuhan yang punya keagungan dan kehormatan. Ya Allah bukakanlah untukku pintu rahmat dan ampunan, masukanlah aku ke dalam ampunanMu. Dengan nama Allah dan segala puji bagi Allah salawat dan salam untuk Rasulullah.", "Sebelum masuk Masjidil Haram, jamaah dianjurkan berwudhu dan masuk lewat pintu mana saja. Nabi Muhammad SAW biasanya masuk lewat pintu Babus Salam atau Bani Syaibah seraya membaca doa.");
        addItem("Doa Sebelum Minum Air Zam - Zam", "اَللّٰهُمَّ إِنِّيْ أْسْأَلُكَ عِلْمً نَافِعًا وَرِزْقًا وَاسِعًا وَشِفَآءً مِنْ كُلِّ دَآءٍ وَسَقَمٍ بِرَحْمَتِكَ يَآ أَرْحَمَ الرَّاحِمِيْنَ", "Allahumma Inni Asaluka 'Ilman Nafi'an Wa Risqon Waasi'an Wa Syifaa'an Min Kulli Daa'in Wa Saqomin Bi Romhatika Ya Arhamar Rohimiin.", "Ya Allah, aku mohon kepadaMu ilmu pengetahuan yang bermanfaat, rizki yang luas dan sembuh dari segala sakit dan penyakit pikun dengan rahmatMu ya Allah yang Maha Pengasih lagi Maha Penyayang.", "Sebelum minum air zam-zam saat melakukan ibadah umroh sebaiknya membaca doa.");
        addItem("Doa Tawaf Putaran Pertama", "سُبْحَانَ اللهِ وَالْحَمْدُ لِلَّهِ وَلَا إِلَهَ إِلَّا اللهَ اللهُ أَكْبَرُ. وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللهِ الْعَلِيِّ الْعَظِيْمِ. وَالصَّلَاةُ وَالسَّلاَمُ عَلَى رَسُولِ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ. اللَّهُمَّ إِيْمَانًا بِكَ وَتَصَدِّيْقًا بِكِتَابِكَ وَوَفَاءاً بِعِبَادِكَ وَاتِّبَاعًا لِسُنَّةِ نَبِيِّكَ مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ. اللَّهُمَّ إِنِّي أَسْئَلُكَ الْعَفْوَى وَالْعَافِيَةَ الدَّائِمَةَ فِي الدِّيْنِ وَالدُّنْيَا وَالْأَخِرَةَ وَالْفَوْزَ بِالْجَنَّةِ وَالنَّجَاةِ مِنَ النَّارِ", "Subahaanallaahi walhamdulillaahi wa laa ilaaha illallaahu allahu akbar. wa laa haula wa laa quwwata illaa billaahil ‘aliyyil ‘azhiimi. Wash shalaatu wassalaamu’alaa rasuulillaaahi shallallaahu ‘alaihi wa sallama. Allahumma iimaanan bika wa tashdiqan bikitaabika wa wafaa’an bi’aadhika wattibaa’an li sunnati nabiyyika muhammadin shallaahu ‘alaihi wa sallama. Allahumma inni as’alukal ‘afwa wal ‘aafiya wal mu’aafatan daaimata fid diini wad dunyaa wal aakhirati wal fauza bil jannati wannajaata minannaari.", "Maha Suci Allah, segala bentuk pujian hanya pantas disanjungkan kepada-Nya, sebab tiada Tuhan selain Allah, zat Yang Maha Besar. Tidak ada daya dan kekuatan kecuali berasal dari sisi-Nya yang Maha Mulia lagi Maha Agung.", "Doa tawaf di putaran pertama, dibaca mulai dari Hajar Aswad sampai Rukun Yamani.");
        addItem("Doa Tawaf Putaran Kedua", "اللَّهُمَّ إِنََ هَذَا الْبَيْتَ بَيْتُكَ وَالْحَرَاَم حَرَامُكَ وَالْأَمْنَ أَمْنُكَ وَالْعَبْدَ عَبْدُكَ وَأَنَا عَبْدُكَ وَابْنُ عَبْدِكَ وَهَذَا مَقَامُ عَيْذُكَ بِكَ مِنْ النَّارِ فَحَرِّمْ لُحُومُنَا وَبَشِّرْنَا عَلَى النَّارِ اللَّهُمَّ حَبِّبْ إِلَيْنَا الْإيْمَانَ وَزَيِّنْهُ فِي قَلُوبِنَا وَكَرِّهْ إِلَيْنَا الْكُفْرَ وَالْفُسُوقَ وَالْعِصْيَانَ وَاجْعَلْنَا مِنَ الرَّاشِدِينَ اللَّهُمَّ قِنِي عَذَابَكَ الْيَوْمَ تَبْعَثُ عِبَادَكَ اللُّهُمَّ ارْزُقْنَا الْجَنَّةَ بِغَيْرِ حِسَابٍ", "Allahumma innaa haadzal baita baituka wal haraama haraamuka wal amna amnuka wal ‘abda ‘abduka wa anaa ‘abduka wabnu ‘abdika wa haadzaa maqaamu ‘aidza bika minannaari faharrim luhuumanaa wa basyaranaa ‘alannaari. Allahumma habbib ilainal iimaana wa zayyinhu fii quluubinaa wa karrih ilainal kufra wal fusuuqa wal ‘ishyaanaa waj’alnaa minar raasyidiina. Allahumma qinii ‘adzaabaka yauma tab’atsu ‘ibaadaka. Allahummarzuqnal jannata bighairi hisaabin.", "Ya Allah, sesungguhnya bait ini rumah-Mu, tanah mulia ini tanah-Mu, negeri aman ini negeri-Mu, hamba ini hamba-Mu, anak dari hamba-Mu, dan tempat ini adalah tempat orang berlindung pada-Mu dari siksa neraka, maka haramkanlah daging dan kulit kami dari siksa api neraka.", "");
        addItem("Doa Tawaf Putaran Ketiga", "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِن الشَّكِّ وَالشِرْكِ والشِّقَاقِ والنِّفَاقِ وسُوءِ الأَخْلاَقِ وَسُوءِ المَنْظَرِ وَالمُنْقَلِبِ فِي المَالِ والأَهْلِ والوَلَدِ اللَّهُمَّ إِنِّي أَسْألُكَ رِضَاكَ والجَنَّةَ وأَعُوذُبِكَ مِن سَخَطِكَ والنَّارِ وَاالهَمِّ إِنِّي أَعُوذُبِكَ مِنْ فِتْنَةِ القُبُرِ وأَعُوذُ بِكَ مِن فِتْنَةِ المَحْيَا والمَمَاتِ", "Allahumma inni a’udzubika minasysyakki wasysyirki wasysyiqaaqi wannifaaqi wa suu’il akhlaaqi wa suu’il manzhari wal munqalabi fil maali wal ahli wal waladi. Allahumma innii as’aluka ridhaaka wal jannata wa a’udzubika min shkathika wannaar. Allahumma innii a’udzubika min fitnatil qabri wa a’udzubika min fitnatil mahyaa wal mamaati.", "Ya Allah, aku berlindung kepada-Mu dari keraguan, syirik, percekcokan, kemunafikan, buruk budi pekerti, penampilan, dan kepulangan yang jelek dalam hubungan dengan harta benda, keluarga dan anak-anak.", "");
        addItem("Doa Tawaf Putaran Keempat", "اللَّهُمَّ اجْعَلْنِي حَجًّا مَبْرُورًا وَسَعْياً مَشْكُورًا وَذُنُباً مَغْفُورًا وَعَمَلًا صَالِحًا مَقْبُولًا وَتِجًارَةً لًنْ تَبُورًا. يَا عَالِمً مَا فِي الصُّدُورِِ أَخْرِجْنِي مِن الظُّلُمَاتِ إِلَى النُورِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ مُوجِبَاتِ رَحْمَتِكَ وَعَزَائِمَ مَغْفِرَتِكَ وَالسَّلاَمَةَ مِن كُلِّ إِثْمٍ والغَنِيمَةَ مِن كُلِّ بِرٍّ والفَوْزَ بِالجَنَّةِ مِن النَّارِ رَبِّي قَنِّعْنِي بِمَا رَزَفَنِي وَبَارِكْ لِي فِيمَا أَعْطَيْتَنِي وَاخْلُفْ عَلَيْنَا كُلَّ غَيْبَةٍ مِنْكَ بِخَيْرٍ", "Allahummaj’alnii hajjan mabruuran wa sa’yan masykuuran wa dzanban maghfuura wa ‘amalan shaalihan maqbuulan wa tijaaratan lan tabuura. Ya ‘aalima maa fish shuduuri akhrijnii minazh zhulumaati ilannuri. ALlahumma inni as ‘aluka mujibaati rahmatika wa ‘azaa’imi maghfiratika wassalaaamata min kulli itsmin wal ghaniimata min kulli birrin wal fauza bil jannati wannajaata minannaari. Rabbi qanni’nii bimaa razaqtanii wa baariklii fiimaa ‘athaitanii wakhluf ‘alaynaa kulla ghaibatin minka bikhairin.", "Ya Allah, karuniakanlah kepada kami haji yang mabrur, Sa’i yang diterima, dosa yang diampuni, amal saleh yang diterima, dan usaha yang tidak mengalami kerugian. Wahai Tuhan Yang Maha Mengetahui segala yang terkandung dalam sanubari, keluarkanlah aku dari kegelapan menuju cahaya yang terang benderang.", "");
        addItem("Doa Tawaf Putaran Kelima", "أللَّهُمَّ أَظِلَّنِي تَحْتَ ظِلِّ عَرْشِكَ يَوْمَ لاَ ظِلَّ إِلَّا ظِلَّكَ وَلَا بَقِيَ إِلَّا وَجْهَكَ وَأَسْفِنِي مِنْ حَوْضِ نَبِيِّكَ مُحَمَّدٍ صَلَّى اللهُ عَلَيْكَ وسَلَّم شُرْبَةً هَنِيئَةً مَرِيئَةً لَا أَظَؤُ بَعْدَهَا أَبَدًا. أللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ خَيْرٍ مَا سَأَلَكَ مِنهُ نَبِيُّكَ مُحَمَّدٌ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ وَأَعُوُذُبِكَ مِنْ شَرِّ مَا عَاذَكَ مِنْهُ نَبِيُّكَ مُحَمَّدٌ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ اللَّهُمَّ إِنِّي أَسْأَلُكَ الجَنَّةَ وَنَعِيمَهَا وَمَا يُقَرِّبُنِي إِلَيْهَا مِنْ قَوْلٍ أَوْ فِعْلٍ أَوْ عَمَلٍ وَأَعُوذُبِكَ مِنَ النَّارِ وَمَا يُقَرِّبُنِي إِلَيْهَا مِنْ قَوْلٍ أَْو فِعْلٍ أَوْ عَمَلٍ", "Allahumma azhillanii tahta zhilli ‘arsyika yauma laa zhilla illaa zhilluka walaa baqiya illaa wajhuka wa asqini min haudhi nabiyyika muhammadin shallallaahu ‘alaihi wasallama syurbatan haniii’atan marii’atan laa azah’u ba’dahaa abadan. Allahumma innii as’aluka min khairi maa sa’alaka minhu nabiyyiuka muhammadun shallallaahu ‘alaihi wa sallama wa a’uudzubika min syarri maa ‘aadzaka minhu nabiyyuka muhammadun shallallahu ‘alaihi wa sallama. Allahumma innii as’alukal jannata wa na’iimahaa wa maa yuqarribunii ilaihaa min qaulin au fi’lin au ‘amalim wa a’udzubika minannaari wa maa yuqaarribunii ilaihaa min qaulin au fi’lin au ‘amalain.", "Ya Allah, lindungilah aku di bawah naungan singgasana-Mu pada hari yang tidak ada naungan selain naungan-Mu, dan tidak ada yang kekal kecuali zat-Mu, dan berilah aku minuman dari telaga Nabi Muhammad SAW dengan suatu minuman yang lezat, segar dan nyaman, sesudah itu aku tidak akan haus untuk selamanya.", "");
        addItem("Doa Tawaf Putaran Keenam", "اللَّهُمَّ إِنَّا لَكَ عَلَيَّ حُقُوقًا كَثِيرًا فِيمَا بَيْنِي وَبَيْنَكَ وَحُقُوقًا كثيرا فِيمَا بَيْنِي وَبَيْنَ خَلْقِكَ الَّلهُمَّ مَا كَانَ لَكَ مِنْهَا فَاغْفِرْهُ لِي وَمَا كَانَ لِخَلْقِكَ وَتَحَمَّلَهُ عَنِّي وَأَغْنِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَبِطَاعَتِكَ عنْ مَعْصِيَتِكَ وَبِفَضْلِكَ عَمَّنْ سِوَاكَ يَا وَاسِعَ المَغْفِرَةِ اللََّهُمَّ إِنَّ بَيْتَكَ عَظِيمٌ وَوَجْهَكَ كَرِيْمٌ وَأَنْتَ يَا اللَّهُمََّ حَلِيمٌ كَرِيمٌ عَظِيمٌ تُحِبُّ العَفْوَ فَاعْفُ عَنَّا", "Allahuma innaa laka ‘alayya huquuqan katsiratan fiima bainii wa bainaka wa huquuqan katsiran fiiimaa bainii wa baina khalqika. Allahumma maa kaana laka minhaa faghfirhu lii wa maa kaana likhalqika fatahammalhu ‘annii wa aghninii bihalaalila ‘an haraamika wa bithaa’atika ‘an ma’shiyyatika wa bidadhlika ‘amman siwaaka yaa waasi’al maghfirati. Allahumma inna baitaka ‘azhiimun wa wajhaka kariimun wa anta yaa allahumma haliimun kariimun ‘azhiimun tuhibbul ‘afwa fa’fu’annii.", "Ya Allah, sesungguhnya Engkau mempunyai hak kepadaku banyak sekali dalam hubunganku dengan Engkau, dan Engkau juga mempunyai hak banyak sekali dalam hubunganku dengan makhluk-Mu. Ya Allah, apa yang menjadi hak-Mu kepadaku, maka ampunilah diriku.", "");
        addItem("Doa Tawaf Putaran Ketujuh", "اللَّهُمَّ إِنِّي أَسْأَلُكَ إِيْمَاناً كَامِلًا وَيَقِينًا صَادِقًا وَرِزْقًا وَاسِعًا وَقَلْبًا خَاشِعًا ولِسَانًا ذَاكِرًا وَحَلَالًا طَيِّبًا وَتَوْبَةً نَصُوحًا وَتَوْبَةً قَبْلَ المَوْتِ وَرَاحَةً عِنْدَ المَوْتِ وَمَغْفِرَةً وَرَحْمَةً بَعْدَ الَموْتِ وَالْعَفْوَ عِنْدَ الحِساَبِ واَلفَوْزَ بِالْجَنَّةِ وَالنَّجَاةِ مِنَ النَّارِ بِرَحْمَتِكَ يَا عَزِيْزُ بِاْلصَالِحِينَ", "Allhumma innii as’aluka iimaanan kaamilan wa yaqiinan shaadiqan wa rizqan waasi’an wa qalban khaasyi’an wa lisaaanan dzaakiran wa halaalan thayyiban wa taubatan nashuuhan wa taubatan qablal mauti wa maghfiratan wa rahmatan ba’dal mauti wal ‘afwa ‘indal hisaabi wal fauza bil jannati wannajaata minannaari birahmatika yaa ‘aziizu bishshaalihin.", "Ya Allah, aku mohon pada-Mu iman yang sempurna, keyakinan yang benar, rizki yang luas, hati yang khusyu, lidah yang selalu berzikir (menyebut nama Allah), rizki yang halal dan baik, taubat yang diterima dan taubat sebelum mati, keampunan dan rahmat sesudah mati, keampunan ketika dihisab, keberuntungan memperoleh surga dan terhindar dari neraka dengan rahmat kasih sayang-Mu, wahai Tuhan Yang Maha Perkasa, Yang Maha Pengampun. Tuhanku, berilah aku tambahan ilmu pengetahuan dan gabungkanlah aku ke dalam golongan orang-orang saleh.", "");
        addItem("Doa Menyelesaikan Tawaf", "اللهم يا رب البيت العتيق أعتق رقابنا ورقاب أبائنا وأمهاتنا وإخواننا وأولادنا من النار ياذا الجود والكرم والفضل والمن والعطاء والإحسان اللهم أحسن عقيبتنا في الأمور كلها وأجرنا من خزي الدنيا وعذاب الأخرة", "Allahuma yaa rabbal baitil ‘atiiqi a’tiq riqaabanaa wa riqaaba aabaa’inaa wa ummahaatinaa wa ikhwaaninaa wa aulaadina minan naari yaa dzal juudi wal karami wal fadhli wal manni wal a’tha’i wal ihsaani. Allahumma ahsin ‘aqiibatanaa fil umuuri hullihaa wa ajirna min khizyiddun-yaa wa ‘adzaabil aakhirati.", "Ya Allah, yang memelihara Ka’bah ini, bebaskanlah diri kami, bapak dan ibu kami, saudara-saudara dan anak-anak kami dari siksa neraka, wahai Tuhan Yang Maha Pemurah, Maha Dermawan, dan yang mempunyai keutamaan, kemuliaan, kelebihan, anugerah, pemberian, serta kebaikan. Ya Allah, perbaikilah akhir segenap urusan kami dan jauhkanlah kami dari kehinaan dunia serta siksa di akhirat kelak.", "");
        addItem("Doa Hendak Melakukan Sa’i", "سْمِ اللهِ الرَّحْمَنِ الرّحِيمِ أَبْدَأُ بِمَا بَدَأَ اللهُ بِهِ وَرَسُولِهِ إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ ۖ فَمَنْ حَجَّ الْبَيْتَ أَوِ اعْتَمَرَ فَلَا جُنَاحَ عَلَيْهِ أَنْ يَطَّوَّفَ بِهِمَا ۚ وَمَنْ تَطَوَّعَ خَيْرًا فَإِنَّ اللَّهَ شَاكِرٌ عَلِيمٌ", "Bismillaahirrahmaanirrahiim. Abda ubimaa bada Allaahu bihi warasuuluh. Innasshafaa wal marwata min sya’aaairillaah. Famanhajjal baita awi’tamarafa laa junaaha ‘alaihi anyathawwa fa bihimaa waman tathawwa ‘a khairan fa innallaaha syaakirun ‘aliimun.", "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Aku mulai dengan apa yang telah dimulai oleh Allah dan Rasul-Nya. Sesungguhnya Shafa dan Marwah sebagian dari syiar-syiar (tanda kebesaran) Allah.", "");
        addItem("Doa Bukit Shafa", "اَللهُ أَكْبَرُ - اَللهُ أَكْبَرُ- اَللهُ أَكْبَرُ لاَ إِلهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيْكَ لَه لَه اْلمُلْكُ وَلَه اْلحَمْدُ وَهُوَ عَلى كُلِّ شَيْئٍ قَدِيْرلآاِلهَ إِلاَّ اللهُ وَحْدَهُ أَ نْجَزَ وَعْدَه ونَصَرَ عَبْدَه وَهَزَمَ اْلأَحْزَابَ وَحْدَه", "Allahu akbar, Allahu akbar, Allahu akbar. Laa ilaaha illallahu wahdahu laa syariikalah, lahul mulku walahul hamdu wahuwa 'alaa kulli syai'in qodiir. Laa ilaaha illallahu wahdah, anjaza wa'dah, wanashoro 'abdah, wahazamal ahzaaba wahdah.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Tiada Tuhan selain Allah Yang Maha Esa, tiada sekutu bagi-Nya, milik-Nya segala kekuasaan, segala puji bagi-Nya, Dialah Yang Maha Kuasa atas segalanya, tiada Tuhan selain Allah Yang Maha Esa, Dia memenuhi janji-Nya, Dia yang menolong hamba-Nya, Dia sendiri yang mengalahkan musuh-Nya.", "Saat tiba di Shafa, kita dianjurkan mengangkat kedua tangan dan menghadap Ka’bah dengan membaca doa.");
        addItem("Doa Sa’i Bukit Shafa ke Marwah", "أَللهُ  أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ , أَللهُ أَكْبَرُ كَبِيْراً وَالحَمْدُ ِللهِ كَثِيْراً وَسُبْحاَنَ اللهِ العَظِيْمِ وَبِحَمْدِهِ الكَرِيْمِ بُكْرَةً وَأَصِيْلاً وَمِنَ اللَّيْلِ فاَسْجُدْ لَهُ وَسَبِّحْهُ لَيْلاً طَوِيْلاً لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ أَنْجَزَ وَعْدَهُ وَنَصَرَ عَبْدَهُ وَهَزَمَ الأَحْزاَبَ وَحْدَهُ لاَ شَيْءَ قَبْلَهُ وَلاَ بَعْدَهُ يُحْيِى وَيُمِيْتُ وَهُوَ حَيٌّ داَئِمٌ لاَ يَمُوْتُ وَلاَ يَفُوْتُ أَبَداً بِيَدِهِ الخَيْرُ وَإِلَيْهِ المَصِيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيْرٌ", "Allahu Akbar, Allahu Akbar, Allahu Akbar, Allahu Akbar kabira, walhamdu lillahi kasira. Wasubhaanallahil'azimi wabiham dihil karimi bukratawwa asila. Waminal laili fasyjud lahu wasabbih-hu lailan tawila. La ilaha illallahu wahdah anjaza wa'dah. Wanasara 'abdah wahazamal ahzaba wahdah. La syai a qablahu wala ba'dahu Yuhyii wayumiitu wahuwa hayyun daa imun layamutu walayafutu abada. Biyadihil khairu wailaihil masiir. Wahuwa'ala kulli syai in qadir.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar, Allah Maha Besar dengan segala kebesaran-Nya. Segala puji bagi Allah Yang Maha Agung dengan segala pujian-Nya yang tidak terhingga. Maha Suci Allah dengan pujian Yang Maha Mulia di waktu pagi dan petang. Bersujud dan bertasbihlah pada-Nya sepanjang malam.", "Doa Sa'i pertama ini dibaca dari bukit Shafa sampai di antara dua pilar atau lampu hijau.");
        addItem("Doa Diantara Dua Pilar", "رَبِّ اغْفِرْ وَارْحَمْ وَاعْفُ وَتَكَرَّمْ وَتَجاَوَزْ عَمَّا تَعْلَمُ إِنَّكَ تَعْلَمُ ماَلاَ نَعْلَمُ إِنَّكَ أَنْتَ اللهُ الأَعَزُّ الأَكْرَمُ", "Rabbighfir warham wa'fu watakarram watajaawaz 'ammaa ta'lamu, innaka ta'lamu, mala na'lamu, Innaka antallahul a'azzul akram.", "Ya Allah, ampunilah, sayangilah, maafkanlah, bermurah hatilah dan hapuskanlah apa-apa yang Engkau ketahui dari dosa kami. Sesungguhnya Engkau Maha Mengetahui apa-apa yang kami sendiri tidak tahu. Sesungguhnya Engkau ya Allah Maha Tinggi dan Maha Pemurah.", "");
        addItem("Doa Saat Mendekati Bukit Marwah", "إِنَّ الصَّفاَ وَالمَرْوَةَ مِنْ شَعَآئِرِ اللهِ , فَمَنْ حَجَّ البَيْتَ أَوِاعْتَمَرَ فَلاَجُناَحَ عَلَيْهِ أَنْ يَّطَّوَّفَ بِهِماَ وَمَنْ تَطَوَّعَ خَيْراً فَإِنَّ اللهَ شاَكِرٌ عَلِيْمٌ", "Inna Shafa wal Marwata min sya'airillah. Faman hajjal bita awi'tamara fala junaha 'alaihi ayyatawwafa bihima. Waman tatawwa'a khairan fainnallaha syakirun 'alim.", "Sesungguhnya Shafa dan Marwah sebagian dari syiar-syiar (tanda kebesaran) Allah. Maka barang siapa yang beribadah haji ke Baitullah ataupun berumrah, tidak ada dosa baginya mengerjakan sa'i antara keduanya. Dan barang siapa mengerjakan sesuatu kebajikan dengan kerelaan hati, maka sesungguhnya Allah Maha menerima kebaikan dan Maha Mengetahui.", "");
        addItem("Doa Lintasan Ke 2 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ وَ ِللهِ الحَمْدُ لاَ إِلَهَ إِلاَّ اللهُ الواَحِدُ الفَرْدُ الصَّمَدُ الَّذِى لَمْ يَتَّخِذْ صاَحِبَةً وَلاَ وَلَداً وَلَمْ يَكُنْ لَهُ شَرِيْكٌ فىِ الْمُلْكِ وَلَمْ يَكُنْ لَهُ وَلِيٌّ مِنَ الذُّلِّ وَكَبِّرْهُ تَكْبِيْراً .أَللَّـهُمَّ إِنَّكَ قُلْتَ فىِ كِتاَبِكَ الْمُنَزَّلِ أُدْعُوْنِى أَسْتَجِبْ لَكُمْ دَعَوْناَكَ رَبَّناَ فاَغْفِرْ لَناَ كَماَ أَمَرْتَناَ إِنَّاكَ لَا تُخْلِيْفُ المِيْعاَدَ . رَبَّناَ إِنَّناَ سَمِعْناَ مُناَدِياً يُناَدِى لِلإِيْماَنِ أَنْ آمِنُوْا بِرَبِّكُمْ فَآَمَنّاَ , رَبَّناَ فاَغْفِرْ لَناَ ذُنُوْبَناَ وَكَفِّرْ عَنَّا سَيِّئَاتِناَ وَتَوَفَّناَ مَعَ الأَبْراَرِ , رَبَّناَ وَأَتِناَ ماَ وَعَدْتَناَ عَلَى رُسُلِكَ وَلاَ تُخْزِناَ يَوْمَ القِياَمَةِ إِنَّكَ لَا تُخْلِفُ الْمِيْعاَدَ . رَبَّناَ عَلَيْكَ تَوَكَّلْناَ وَإِلَيْكَ أَنَبْناَ وَإَلَيْكَ الْمَصِيْرُ . رَبَّناَ اغْفِرْ لَناَ ذُنُوْبَناَ وَ ِلإِخْواَنِناَ الَّذِيْنَ سَبَقُوْناَ بِالإِيْماَنِ وَلاَ تَجْعَلْ فىِ قُلُوْبِناَ غِلاًّ لِّلَّذِيْنَ أَمَنُوْا رَبَّناَ إِنَّاكَ رَءُوْفٌ رَّحِيْمٌ", "Allahu Akbar Allahu Akbar Allahu Akbar walillahil hamdu. Laa ilaaha illallaahul waahidul fardus shamad. Allazi lam yattakhiz shaahibatan walaa waladan walam yakun lahu syarikun fil mulki walam ya kun lahu waliyyun minazzulli wakabbirhu takbira. Allahumma innaka kulta fi kitabikal munazali ud'uni astajib lakum da'aunaka rabbana `fagfir lana kama amartana innaka latukhliful mi'ad. Rabbana innana sami'na munadiyan yunadi lil imani anaminu birabbikum fa'amanna. Rabana fagfirlana zunubana wa kaffir 'anna sayyiatina watawaffana ma'al abrar. rabbana wa atina mawa'ad tana ala rusulika wala tukhzina yaumal qiyamati innaka latukhliful mi'ad. Rabbana 'alaika tawakkalna wailaika anabna wailaikal masir. Rabbanagfirlana zunuwali ikhwaninal lazina sabaquna bil imani wala taj'al fi qulubina gillal lillazina amanu rabbana innaka ra ufurrahim.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar, hanya bagi Allah segala pujian. Tidak ada Tuhan selain Allah yang Maha Esa, Tunggal, dan Tumpuan segala maksud dan hajat, yang tidak beristri dan tidak beranak, tidak bersekutu dalam kekuasaan, dan tidak menjadi pelindung kehinaan. Agungkanlah Dia dengan segenap kebesaran.", "");
        addItem("Doa Lintasan Ke 3 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ وَ ِللهِ الحَمْدُ رَبَّناَ أَتْمِمْ لَناَ نُوْرَناَ وَاغْفِرْ لَناَ إِنَّكَ عَلَى كُلِّ شَيْءٍ قَدِيْرٌ . أَللَّـهُمَّ إِنِّى أَسْأَلُكَ الخَيْرَ كُلَّهُ عاَجِلَهُ وَأَجِلَهُ وَأَسْتَغْفِرُكَ لِذَنْبِى وَأَسْأَلُكَ رَحْمَتَكَ ياَ أَرْحَمَ الرَّحِمِيْنَ", "Allahu akbar, Allahu Akbar, Allahu Akbar walillahil hamdu, Rabbana atmim lana nurana waghfirlana innaka 'ala kulli syai-in qadir. Allahumma inni as alukal khaira kullahu 'aajilahu wa ajilahu wa astagfiruka lidzanbii wa-asaluka rahmataka yaa-arhamar rahimin.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Hanya bagi Allah semua pujian. Ya Allah, sempurnakanlah cahaya terang bagi kami, ampunilah kami, sesungguhnya Engkau Maha Kuasa atas segala sesuatu. Ya Allah, sesungguhnya aku mohon pada-Mu segala kebaikan yang cepat atau lambat dan aku mohon ampunan pada-Mu akan dosaku, serta aku mohon pada-Mu, rahmat-Mu wahai Tuhan yang Maha Pengasih dari segenap yang pengasih.", "");
        addItem("Doa Lintasan Ke 4 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ وَ ِللهِ الحَمْدُ أَللَّـهُمَّ إِنِّى أَسْأَلُكَ مِنْ خَيْرِ ماَتَعْلَمُ وَأَعُوْذُ بِكَ مِنْ شَرِّ ماَ تَعْلَمُ وأَسْتَغْفِرُكَ مِنْ كُلِّ ماَ تَعْلَمُ إِنَّاكَ أَنْتَ عَلاَّمُ الغُيُوْبِ , لاَ إِلَهَ إِلاَّ اللهُ المَلِكُ الحَقُّ المُبِيْنُ , مُحَمَّدٌ رَسُوْلُ اللهِ صاَدِقُ الوَعْدِ الأَمِيْنُ . أَللَّـهُمَّ إِنِّى أَسْأَلُكَ كَماَ هَدَيْتَنِى لِلإِسْلاَمِ أَنْ لاَتَنْزِعَهُ مِنِّى حَتَّى تَتَوَفَّنِى وَأَناَ مُسْلِمٌ , أَللّهُمَّ اجْعَلْ فىِ قَلْبِى نُوْراً وَفىِ سَمْعِى نُوْراً وَفىِ بَشَرِى نُوْراً , أَللَّـهُمَّ اشْرَحْ لىِ صَدْرِى وَيَسِّرْ لىِ أَمْرِى وَأَعُوْذُ بِكَ مِنْ وَساَوِسِ الصَّدْرِ وَشَتاَتِ الأَمْرِ وَفِتْنَةِ القَبْرِ , أَللَّـهُمَّ إِنِّى أَعُوْذُ بِكَ مِنْ شَرِّ ماَ يَلِجُ فىِ اللَّيْلِ وَشَرِّ ماَ يَلِجُ فىِ النَّهاَرِ وَمِنْ شَرِّ ماَ تَهُبُّ بِهِ الرِّياَحُ ياَ أَرْحَمَ الرَّحِمِيْنَ . سُبْحاَنَكَ ماَ عَبَدْناَكَ حَقَّ عِباَدَتِكَ ياَ أَللهُ سُبْحاَنَكَ ماَذَكَرْناَكَ حَقَّ ذِكْرِكَ ياَ أَللهُ", "Allahu Akbar Allahu Akbar Allahu Akbar walillahil hamdu. Allahumma inni as aluka min khairi ma ta'lamu wa a'uzubika min syarri mata'lamu wa astagfiruka min kulli mata'lamu innaka anta 'allamul guyub. La ilaha illallahul malikul haqqul mubin. Muhammadur rasulullah sadiqul wa'dil amin. Allahumma inni as aluka kama haditani lil islami an la tanzi 'ahu minni hatta tatawaffani wa ana muslimun. Allahummaj'al fi qalbi nura. Allahummasyroh li sadri wayassirli amri wa a'uzubika min wasawisis sadri wasyatatil amri wafit natil qabri. Allahumma inni a'uzubika min syarri ma yaliju fillaili wa syarri ma yaliju finnahari wamin syarri matahubbu bihir riyahu ya arhamar rahimin. Subhanaka ma 'abadnaka haqqa ibadatika ya Allahu Subhanaka ma zakarnaka haqqa zikrika ya Allahu.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Segala puji bagi Allah. Ya Allah Tuhanku, aku mohon pada-Mu dari kebaikan yang Engkau tahu dan berlindung pada-Mu dari kejahatan yang Engkau tahu, dan aku mohon ampun pada-Mu dari segala kesalahan yang Engkau ketahui, sesungguhnya Engkau Maha mengetahui yang gaib.", "");
        addItem("Doa Lintasan Ke 5 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ وَ ِللهِ الحَمْدُ سُبْحاَنَكَ ماَ أَعْلَى شَأْنَكَ ياَ أَللهُ , أَللَّـهُمَّ حَبِّبْ إِلَيْناَ الإِيْماَنَ وَزَيِّنْهُ فىِ قُلُوْبِناَ وَكَرِّهْ إِلَيْناَ الكُفْرَ وَالفُسُوْقَ وَالْعِصْيَانَ وَاجْعَلْناَ مِنَ الرَّاشِدِيْنَ", "Allahu Akbar Allahu Akbar Allahu Akbar walillahil hamdu. Subhanaka ma syakarnaaka haqqa syukrika ya Allahu subhanaka ma a'la sya'naka ya Allahu. Allahumma habbib ilainal imana wa zayyinhu fi qulubina wakarrih ilainal kufra walfu suqa wal'isyana waj'alna minar rasyidin.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Hanya untuk Allah segala puji. Maha Suci Engkau seperti kami bersyukur pada-Mu sebenar-benar syukur wahai Allah. Maha Suci Engkau sepadan ketinggian-Mu wahai Allah. Ya Allah dekatkan kami kepada iman dan hiaskanlah di hati kami, jauhkan kami pada perbuatan kufur, fasiq dan durhaka. Masukanlah kami ke dalam golongan orang-orang yang mendapat petunjuk.", "");
        addItem("Doa Lintasan Ke 6 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ وَ ِللهِ الحَمْدُ لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ صَدَقَ وَعْدَهُ وَنَصَرَ عَبْدَهُ وَهَزَمَ الأَحْزاَبَ وَحْدَهُ لاَ إِلَهَ إِلاَّ اللهُ وَلاَ نَعْبُدُ إِلاَّ إِياَّهُ مُخْلِصِيْنَ لَهُ الدِّيْنَ وَلَوْ كَرِهَ الكاَفِرُوْنَ . أَللَّـهُمَّ إِنِّى أَسْأَلُكَ الهُدَى وَالتُّقَى وَالعَفاَفَ وَالغِنَى , أَللَّـهُمَّ لَكَ الحَمْدُ كاَلَّذِىْ نَقُوْلُ وَخَيْراً مِمَّا نَقُوْلُ , أَللَّـهُمَّ إِنِّى أَسْأَلُكَ رِضاَكَ وَالجَنَّةَ وَأَعُوْذُ بِكَ مِنْ سَخَطِكَ وَالنَّارِ وَماَ يُقَرِّبنُِى إِلَيْهاَ مِنْ قَوْلٍ أَوْ فِعْلٍ أَوْ عَمَلٍ . أَللَّـهُمَّ بِنُوْرِكَ اهْتَدَيْناَ وَبِفَضْلِكَ اسْتَغْنَيْناَ وَفىِ كَنَفِكَ وَإِنْعاَمِكَ وَعَطاَئِكَ وَإِحْساَنِكَ أَصْبَحْناَ وَأَمْسَيْناَ أَنْتَ الأَوَّلُ فَلاَ قَبْلَكَ شَيْءٌ وَالأَخِرُ فَلاَ بَعْدَكَ شَيْءٌ وَالظَّاهِرُ فَلاَ شَيْءَ فَوْقَكَ وَالباَطِنُ فَلاَ شَيْءَ دُوْنَكَ نَعُوْذُ بِكَ مِنَ الفَلَسِ وَالكَسَلِ وَعَذاَبِ القَبْرِ وَفِتْنَةِ الغِنَى وَنَسْأَلُكَ الفَوْزَ بِالجَنَّةِ", "Allahu Akbar Allahu Akbar Allahu Akbar walillahil hamdu. La ilaha illallahu wahdah, sadaqa wa'dah, wanasara 'abdah wahazamal ahzaba wahdah. La ilaha illallahu wala na'budu illa iyyahu mukhlisina lahuddina walau karihal kafirun. Allahumma inni 'as'alukal huda wattuqa wal 'afafa walgina. Allahumma lakal hamdu kallazi naqulu wakhairan mimma naqulu. Allahumma inni as'aluka ridaka waljannata wa a'uzubika min sakhatika wannari wama yuqarribuni ilaiha min qaulin aufi'lin au'a malin. Allahumma binurikah tadaina wabifadlika istagnaina wa fi kanafika wa in amika wa'ata ika wa ihsanika asbahna wa amsaina antal awwalu fala qablaka syai'un wal akhiru fala ba'daka syai'un wazzahiru fala syai'a dunaka na'uzubika minal falasi wal kasali wa'azabil qabri wafitnatil gina wa nas'alukal fauza biljannah.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar, segala puji hanya untuk Allah. Tidak ada Tuhan selain Allah Yang Maha Esa, yang menepati janji-Nya, menolong hamba-Nya dan menghancurkan musuh dengan kekuasaan-Nya. Tiada Tuhan yang disembah selain Allah.", "");
        addItem("Doa Lintasan Ke 7 Bukit Shafa Ke Marwah", "أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ أَللهُ أَكْبَرُ كَبِيْراً وَالحَمْدُ ِللهِ كَثِيْراً , أَللَّـهُمَّ حَبِّبْ إِلَيَّ الإِيْماَنَ وَزَيِّنْهُ فىِ قَلْبِى وَكَرِّهْ إِلَيَّ الكُفْرَ وَالفُسُوْقَ وَالعِصْياَنَ وَاجْعَلْنِى مِنَ الرَّاشِدِيْنَ", "Allahu Akbar Allahu Akbar Allahu Akbar kabira walhamdu lillahi kasira. Allahumma habbib ilayyal imana wazayyinhu fi qalbi wakarrih ilayyal kufra wal fusuqa wal 'isyana waj'alni minar rasyidin.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Segala puji kembali kepada Allah. Ya Allah buatlah aku cinta kepada iman, hiaskanlah ia dikalbuku. Jauhkan aku pada perbuatan kufur, fasiq, dan durhaka. Dan masukkanlah pula aku dalam golongan orang yang mendapat petunjuk.", "");
        addItem("Doa Setelah Melakukan Sa’i","أَللَّـهُمَّ رَبَّناَ تَقَبَّلْ مِنَّا وَعاَفِناَ وَاعْفُ عَنَّا وَعَلَى طاَعَتِكَ وَشُكْرِكَ أَعِنَّا وَعَلَى غَيْرِكَ لاَ تَكِلْناَ وَعَلَى الإِيْماَنِ وَالإِسْلاَمِ الكاَمِلِ جَمِيْعاً تَوَفَّناَ وَأَنْتَ راَضٍ عَنَّا أَللَّـهُمَّ ارْحَمْنِى بِتَرْكِ المَعاَصِى أَبَداً ماَ أَبْقَيْتَنِى وَارْحَمْنِى أَنْ أَتَكَلَّفَ ماَ لاَ يَعْنِيْنِى وَارْزُقْنِى حُسْنَ النَّظَرِ فِيْماَ يُرْضِيْكَ عَنِّى ياَ أَرْحَمَ الرَّاحِمِيْنَ", "Allahumma rabbana taqabbal minna wa'afina wa,fu 'anna wa'ala tha atika wasyukrika a'inna wa'ala ghairika latakilna wa alal imani wal islamil kamili jami'an, tawaffana wa anta radin anna. Allahummar hamni bitarkil ma'asi abadan ma abqaitani warhamni an atakalaffa ma la ya'nini warzugni husnan nazari fima yurdika anni ya arhamar rahimin.", "Ya Allah, kami mohon diterima doa kami, afiatkan dan ampunilah kami, berilah pertolongan kepada kami untuk taat dan bersyukur kepada-Mu. Janganlah Engkau jadikan kami bergantung selain kepada-Mu. Matikanlah kami dalam Islam yang sempurna dalam keridoan-Mu.", "");
        addItem("Doa Sebelum Memotong Rambut", "اَللهُ اَكْبَرْ اَللهُ اَكْبَرْ اَللهُ اَكْبَرْ اَلْحَمْدُ للهِ عَلَى مَا هَدَانَا وَالْحَمْدُ للهِ عَلَى مَا أَنْعَمَنَابِهِ عَلَيْهَا. اَللَّهُمَّ هَذِهِ نَاصِيَتِي فَتَقَبَّلْ مِنِّي وَاغْفِرْ ذُنُوْبِى اَللََّهُمَّ اغْفِرْ لِلْمُحَلِّقِيْنَ وَاْلمَقْصُوْرِيْنَ يَاوَاسِعَ الْمَغْفِرَةٍ اَللَّهُمَّ اثْبُتْ لِى بِكُلِّ شَعْرَةٍ حَسَنَةً وَامْحُ عَنِّي بِهَا سَيِّئَةً. وَارْفَعْ لِىْ بِهَا عِنْدَكَ دَرَجَةً", "Allaahu akbar Allaahu akbar Allaahu akbar. Wal hamdulilillahi ‘ala maa hadaanaa wal hamdu lillaahi ‘ala maa an’amanaa bihi ‘alainaa. Allaahumma haadzihi naashiyatiiy fataqabbal minna waghfir dzhunubiiy. Allaahummaghfirlil muhallaqiina walmuqasshariina yaa waasi’al maghfirah. Allaahummatsbut liiy bikulla sya’ratin hasanatan wamhu ‘anna bihaa sayya’atan, warfa’liiy bihaa ‘indaka darajah.", "Allah Maha Besar, Allah Maha Besar, Allah Maha Besar. Segala puji bagi Allah yang telah memberi petunjuk kepada kita dan segala puji bagi Allah tentang apa-apa yang telah Allah karuniakan kepada kami.", "");
        addItem("Doa Setelah Memotong Rambut", "اَلْحَمْدُ للهِ الَّدِى قَضَى عَنَا مَنَاسِكَنَا. اَللَّهُمَّ زِدْنَا اِيْمَانَا وَيَقِيْنَا وَعَوْنَا وَاغْفِرْ لَنَا وَلِوَالِدَيْنَا وَلِسَائِرِ اْلمُسْلِمِيْنَ وَاْلمُسْلِمَاتِ", "Alhamdulillaahil ladzii qadla ‘annaa manaasikanaa, Allaahumma zidnaa iimaanan wayaqiinan wa ‘awnan, waghfirlanaa wali wali daynaa walisaairil muslimiina walmuslimaat.", "Segala puji bagi Allah yang telah menyelesaikan manasik kami, Ya Allah tambahkanlah kepada kami iman, keyakinan, dan pertolongan dan ampunilah kami, kedua orang tua kami dan seluruh kaum muslimin dan muslimat.", "");


        doaHajiUmrahAdapter = new DoaHajiUmrahAdapter(models);
        recyclerViewDoaUmrah.setAdapter(doaHajiUmrahAdapter);
    }

    private void addItem(String title, String arabic, String translate, String arti, String keterangan) {
        models.add(new DoaHajiUmrahModel(title, arabic, translate, arti, keterangan));
    }

    @Override
    public boolean onSupportNavigateUp() {
        onBackPressed();
        return true;
    }
}