package com.tomboati.tour.view.activity.doa_dzikir;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import com.tomboati.tour.adapter.AsmaulHusnaAdapter;
import com.tomboati.tour.databinding.ActivityNewAsmaulHusnaBinding;
import com.tomboati.tour.model.AsmaulHusnaModel;
import com.tomboati.tour.view.activity.base.BaseToolbarActivity;

import java.util.ArrayList;
import java.util.List;

public class NewAsmaulHusnaActivity extends BaseToolbarActivity {

    private ActivityNewAsmaulHusnaBinding bind;

    @Override
    protected void onViewReady(Bundle savedInstanceState, Intent intent) {
        super.onViewReady(savedInstanceState, intent);
        bind = ActivityNewAsmaulHusnaBinding.inflate(getLayoutInflater());
        setToolbar(bind.toolbar, "Asmaul Husna");

        List<AsmaulHusnaModel> list = new ArrayList<>();
        list.add(new AsmaulHusnaModel("","الله","Allah","Allah","Lafaz yang Maha Mulia yang merupakan nama dari Zat Ilahi yang Maha Suci serta wajib adanya yang berhak memiliki semua macam pujian dan sanjungan. Lafadz ini disebut juga lafadz Jalalah, dan juga disebut Ismu Zat. Yaitu Zat yang menciptakan langit, bumi dan seisinya termasuk kita sebagai umat manusia ini. Dan Dia lah Tuhan seluruh alam.","Jika dibaca 100 kali setiap hari setelah selesai shalat, jika Allah Menghendaki, maka kedengkian dan kelalaian dalam hati pembaca akan berubah."));
        list.add(new AsmaulHusnaModel("1", "الرحمن", "Ar Rahman", "Yang Maha Pengasih","Maha Pengasih, yaitu pemberi kenikmatan yang agung-agung dan pengasih di dunia.","Jika kita membaca Yaa Rahmaan sebanyak 100x, yaitu setiap usai mengerjakan shalat fardu. Dengan seizin Allah kita akan memiliki ingatan yang kuat, pengetahuan yang cemerlang, dan terhindar dari hati yang keras."));
        list.add(new AsmaulHusnaModel("2", "الرحيم", "Ar Rahiim", "Yang Maha Penyayang","Maha Penyayang, yaitu pemberi kenikmatan dan penyayang.","Barangsiapa membaca Yaa Rahiim 100x seusai shalat subuh, dengan seizin Allah, setiap orang akan bersahabat dan baik kepadanya. Dan bila dibaca tujuh kali maka ia akan berada dalam naungan Allah. Kemudian bila setiap usai shalat fardu dibaca seratus kali maka Allah akan mengasihinya."));
        list.add(new AsmaulHusnaModel("3", "الملك", "Al Malik", "Yang Maha Merajai / Memerintah","Maha Merajai / Menguasai / Pemerintah, yaitu mengatur kerajaan-Nya sesuai dengan kehendak-Nya sendiri.","Perbanyaklah membaca Yaa Maalik. Dengan seizin Allah, kita akan diberi kekuatan, kekuasaan, kebesaran, serta kepemilikan atas segala sesuatu. Orang-orang akan memberlakukan kita dengan baik dan penuh hormat."));
        list.add(new AsmaulHusnaModel("4", "القدوس", "Al Quddus", "Yang Maha Suci","Maha Suci, yaitu tersuci dan bersih dari segala cela dan kekurangan.","Bila Yaa Qudduus dibaca seratus kali setiap hari, dengan seizin Allah, hati orang yang membacanya akan terbebas dari rasa gundah dan gelisah. Orang yang setiap hari rutin membaca zikir ini akan mendapat kejernihan hati yang sempurna."));
        list.add(new AsmaulHusnaModel("5", "السلام", "As Salaam", "Yang Maha Memberi Kesejahteraan","Maha Penyelamat, yaitu pemberi keselamatan dan kesejahteraan kepada seluruh makhlukNya.","Apabila Yaa Salaam dibaca sebanyak 160 kali untuk orang yang sakit, dengan seizin Allah, orang yang sakit tersebut akan segera disembuhkan dari penyakitnya. Sering mengucapkan bacaan ini juga akan mendatangkan cinta dan keselamatan serta keamanan dari segala macam bencana."));
        list.add(new AsmaulHusnaModel("6", "المؤمن", "Al Mu`min", "Yang Maha Memberi Keamanan","Maha Pengaman / Pemelihara keamanan, yaitu siapa yang bersalah dan makhlukNya itu benar-benar akan diberi siksa, sedang kepada yang taat akan benar-benar dipenuhi janji-Nya dengan pahala yang baik.","Barangsiapa sering membaca Yaa Mu`min, dengan seizin Allah, ia akan terbebas dari segala macam gangguan yang mungkin menghadangnya."));
        list.add(new AsmaulHusnaModel("7", "المهيمن", "Al Muhaimin", "Yang Maha Pemelihara","Maha Pelindung / Penjaga / Maha Pengawal serta Pengawas, yaitu memerintah dan melindungi segala sesuatu.","Barang siapa membaca Yaa Muhaimin dalam kondisi suci (wudhunya belum batal), dengan seizin allah, batinnya bakal memancarkan cahaya. Dan barang siapa melafalkan bacaan ini 125 kali, Insya Allah, hatinya akan menjadi jernih. Ia akan menemukan rahasia dan hakikat dari setiap kejadian."));
        list.add(new AsmaulHusnaModel("8", "العزيز", "Al `Aziiz", "Yang Maha PerkasaYang Maha Perkasa","Maha Mulia / Maha Berkuasa, yaitu kuasaNya mampu untuk berbuat sekehendakNya","Seseorang yang mengamalkan bacaan Yaa `Aziiz sebanyak empat puluh kali setiap usai shalat subuh selama empat puluh hari, dengan seizin Allah, dirinya tidak akan bergantung kepada orang lain. Dana barang siapa yang setiap hari setelah terbitnya fajar melafalkan bacaan ini 94 kali, maka Insya Allah, ia akan dianugerahi kewibawaan."));
        list.add(new AsmaulHusnaModel("9", "الجبار", "Al Jabbar", "Yang Memiliki Mutlak Kegagahan","Maha Perkasa / Maha Kuat / Yang Menundukkan Segalanya, yaitu mencukupi segala keperluan, melangsungkan segala perintahNya serta memperbaiki keadaan seluruh hambaNya.","Siapa saja yang sering membaca bacaan Yaa Jabbaar, dengan seizin Allah, ia tidak akan dipaksa oleh siapapun untuk melakukan perbuatan yang tidak ia inginkan. Ia akan terlindung dari berbagai bentuk kekerasan, kekejian, dan kekejaman."));
        list.add(new AsmaulHusnaModel("10", "المتكبر", "Al Mutakabbir", "Yang Maha Megah, Yang Memiliki Kebesaran","Maha Megah / Maha Pelengkap Kebesaran. yaitu yang melengkapi segala kebesaranNya, menyendiri dengan sifat keagungan dan kemegahanNya.","Orang tua yang gemar membaca Yaa Mutakabbir berulang kali, dengan seizin Allah akan diberikan kepadanya anak-anak yang saleh."));
        list.add(new AsmaulHusnaModel("11", "الخالق", "Al Khaliq", "Yang Maha Pencipta","Maha Pencipta, yaitu mengadakan seluruh makhluk tanpa asal, juga yang menakdirkan adanya semua itu.","Barangsiapa membaca Yaa Khaaliq berulang-ulang di malam hari, Insya Allah, Allah akan menciptakan satu malaikat yang bertugas melakukan amal kebaikan untuk orang tersebut. Di hari hisab, pahala amal kebaikan sang malaikat akan diberikan kepada orang itu. Dan siapa yang membaca Asma Allah ini sebanyak 100 kali selama 7 hari, ia akan dilindungi dari semua malapetaka, Insya Allah."));
        list.add(new AsmaulHusnaModel("12", "البارئ", "Al Baari`", "Yang Maha Melepaskan (Membuat, Membentuk, Menyeimbangkan)","Maha Pembuat / Maha Perancang / Maha Menjadikan, yaitu mengadakan sesuatu yang bernyawa yang ada asal mulanya.","Jika Seorang wanita yang mandul berpuasa selama 7 hari dan setiap hari setelah berbuka dengan air kemudian membaca Yaa Baari’uu yaa Mushawwiru sebanyak 21 kali, Allah SWT akan mengaruniakan kepadanya seorang anak lelaki, Insya Allah. Barang siapa membaca Asma Allah ini selama 7 hari berturut – turut sebanyak 100 kali maka ia akan selamat dari bencana."));
        list.add(new AsmaulHusnaModel("13", "المصور", "Al Mushawwir", "Yang Maha Membentuk Rupa (makhluknya)","Maha Pembentuk / Maha Menjadikan Rupa Bentuk, memberikan gambaran atau bentuk pada sesuatu yang berbeza dengan lainnya. (Al-Khaaliq adalah mengadakan sesuatu yang belum ada asal mulanya atau yang menakdirkan adanya itu. Al-Baari` ialah mengeluarkannya dari yang sudah ada asalnya, manakala Al-Mushawwir ialah yang memberinya bentuk yang sesuai dengan keadaan dan keperluannya).","Jika seorang wanita yang tidak dapat memiliki anak dan percaya bahwa hanya Allah lah Yang Maha Pencipta, kemudian dia berpuasa selama 7 hari dan setiap berbuka puasa membaca yaa Khaaliq yaa Baarii’ yaa Mushawwir sebanyak 21 kali diatas segelas air dan berbuka puasa dengan meminum air ini, Insya Allah dia akan memiliki anak."));
        list.add(new AsmaulHusnaModel("14", "الغفار", "Al Ghaffaar", "Yang Maha Pengampun","Maha Pengampun, banyak pemberian maafNya dan menutupi dosa-dosa dan kesalahan.","Orang yang mengamalkan bacaan Yaa Ghaffaar berulang-ulang, dengan seizin Allah, dosa dan kesalahannya akan dihapuskan."));
        list.add(new AsmaulHusnaModel("15", "القهار", "Al Qahhaar", "Yang Maha Menundukan","Maha Pemaksa, menggenggam segala sesuatu dalam kekuasaanNya serta memaksa segala makhluk menurut kehendakNya.","Seseorang yang membaca Yaa Qohhaar berulang-ulang, dengan seizin Allah, ia akan mendapatkan beberapa kelebihan. Jiwanya mampu menaklukkan hawa nafsu, hatinya tidak cenderung pada dunia, dan batinnya akan merasa tenang. Bacaan ini juga bisa menjaga seseorang dari kezaliman orang lain."));
        list.add(new AsmaulHusnaModel("16", "الوهاب", "Al Wahhaab", "Yang Maha Pemberi Karunia","Maha Pemberi / Maha Menganugerah, yaitu memberi banyak kenikmatan dan selalu memberi kurnia.","Orang yang membaca Yaa Wahhaab tujuh kali setelah berdoa, Insya Allah doanya akan terkabul. Bila mempunyai kebutuhan atau kekurangan materi, bila membaca asma ini 100 kali setelah shalat malam dalam keadaan suci selama tiga hari atau tujuh malam, maka Allah SWT akan mencukupi seluruh kebutuhannya."));
        list.add(new AsmaulHusnaModel("17", "الرزاق", "Ar Razzaaq", "Yang Maha Pemberi Rezeki","Maha Pengrezeki / Maha Pemberi Rezeki, yaitu memberi berbagai rezeki serta membuat juga sebab-sebab diperolehnya.","Jika seseorang benar – benar percaya bahwa rezeki kita berasal dari Allah, dan bahwa rumah tangganya membutuhkan rezeki tersebut, maka setiap selesai melaksanakan sholat subuh dia dapat membaca yaa Razzaaq sebanyak 10 kali di keempat sudut rumahnya, dimulai dari sudut kanan dan menghadap kiblat. Allah akan menambahkan rezeki keluarganya. Membaca yaa Razzaaq sebanyak 100 kali setelah sholat jumat akan membantu orang yang mengalami stres dan depresi."));
        list.add(new AsmaulHusnaModel("18", "الفتاح", "Al Fattaah", "Yang Maha Pembuka Rahmat","Maha Membukakan / Maha Pembuka, yaitu membuka gedung penyimpanan rahmatNya untuk seluruh hambaNya.","Barangsiapa ingin hatinya dibuka dan memperoleh kemenangan, perbanyaklah melafalkan Yaa Fattaah. Usai shalat subuh bacalah lafal ini tujuh puluh kali kemudian letakkan tangan di atas dada. Maka kegelapan yang ada di hati akan sirna. Bila dibaca rutin, lafal ini akan bermanfaat untuk memudahkan semua pekerjaan."));
        list.add(new AsmaulHusnaModel("19", "العليم", "Al `Aliim", "Yang Maha Mengetahui (Memiliki Ilmu)","Maha Mengetahui, yaitu mengetahui segala yang maujud dan tidak ada satu benda pun yang tertutup oleh penglihatanNya.","Barangsiapa sering membaca Yaa `Aliim, hatinya akan cemerlang dan mampu menyingkapkan cahaya Ilahi. Bacaan ini memiliki manfaat yang besar guna mendapatkan ilmu dan menampakkan hal-hal yang tersembunyi. Melafalkan bacaan ini sepuluh kali setiap selesai shalat, Insya Allah, akan membuka hal-hal yang ghaib. Jika seseorang melazinkan membaca Asma Allah ini sebanyak 150 kali setiap hari, niscaya pemikiran dan pemahamannya akan bertambah. Barang siapa membaca Asma Allah ini sebanyak 100 kali secara rutin setiap selesai sholat fardhu, maka ia akan memperoleh kemampuan untuk melihat hal – hal tertentu yang luput dari perhatian orang dan memiliki iman yang kuat. Di samping itu, hatinya akan dipenuhi dengan ma’rifatullahi (mengenal Allah)."));
        list.add(new AsmaulHusnaModel("20", "القابض", "Al Qaabidh", "Yang Maha Menyempitkan (makhluknya)","Maha Pencabut / Maha Penyempit Hidup / Maha Pengekang, yaitu mengambil nyawa atau menyempitkan rezeki bagi siapa yang dikehendaki olehNya.","Barangsiapa menuliskan Yaa Qaabidh di atas lima puluh makanan (buah, roti, dan sebagainya) selama empat puluh hari. Dengan seizin Allah, ia tidak akan kelaparan. Bahkan ia akan mendapatkan limpahan rezeki. "));
        list.add(new AsmaulHusnaModel("21", "الباسط", "Al Baasith", "Yang Maha Melapangkan (makhluknya)","Maha Meluaskan / Maha Pelapang Hidup / Maha Melimpah Nikmat, yaitu memudahkan terkumpulnya rezeki bagi siapa yang diinginkan olehNya.","Barangsiapa membaca Yaa Baasith sepuluh kali di waktu fajar, setelah shalat subuh, dengan tangan terbuka (telapak tangan menghadap ke atas) lalu mengusap wajahnya dengan tangan. Maka, dengan seizin Allah, ia tidak akan bergantung kepada orang lain serta akan memperoleh kekayaan. "));
        list.add(new AsmaulHusnaModel("22", "الخافض", "Al Khaafidh", "Yang Maha Merendahkan (makhluknya)","Maha Menjatuhkan / Maha Menghinakan / Maha Perendah / Pengurang, yaitu terhadap orang yang selayaknya dijatuhkan akibat kelakuannya sendiri dengan memberinya kehinaan, kerendahan dan seksaan.","Barangsiapa ingin terbebas dari kejahatan musuh, berpuasalah selama tiga hari. Kemudian pada hari keempatnya membaca Yaa Khaafidh sebanyak 70 ribu kali. Orang yang mengamalkan asma ini sebanyak tujuh puluh kali, Allah SWT akan menjaganya dari kejahatan orang-orang yang zalim. "));
        list.add(new AsmaulHusnaModel("23", "الرافع", "Ar Raafi`", "Yang Maha Meninggikan (makhluknya)","Maha Mengangkat / Maha Peninggi, yaitu terhadap orang yang selayaknya diangkat kedudukannya kerana usahanya yang giat, yaitu termasuk golongan kaum yang bertaqwa.","Barangsiapa mengamalkan bacaan Yaa Raafi` seratus kali setiap hari, siang atau malam, maka Allah akan memuliakan orang tersebut serta memberinya kekayaan dan kebaikan."));
        list.add(new AsmaulHusnaModel("24", "المعز", "Al Mu`izz", "Yang Maha Memuliakan (makhluknya)","Maha Menghormati / Memuliakan / Maha Pemberi Kemuliaan/Kemenangan, yaitu kepada orang yang berpegang teguh pada agamaNya dengan memberinya pentolongan dan kemenangan.","Jika Yaa Mu`izz dibaca 140 kali setelah shalat Isya, yaitu pada malam senin dan jum`at, maka Allah akan membuat hamba yang membacanya menjadi mulia dan terhormat di mata orang lain. Orang tersebut tidak akan memiliki rasa takut kepada siapapun, selain kepada Allah SWT. "));
        list.add(new AsmaulHusnaModel("25", "المذل", "Al Mudzil", "Yang Maha Menghinakan (makhluknya)","Maha Menghina / Pemberi kehinaan, yaitu kepada musuh-musuhNya dan musuh ummat Islam seluruhnya.","Barangsiapa mengamalkan Yaa Mudzill sebanyak 75 kali, Insya Allah, dirinya akan terbebas dari gangguan orang-orang yang iri padanya, serta dari orang yang berniat untuk mencelakainya. Ia akan selalu dilindungi oleh Allah SWT. "));
        list.add(new AsmaulHusnaModel("26", "السميع", "Al Samii`", "Yang Maha Mendengar","Maha Mendengar.","Barangsiapa membaca Yaa Samii` pada hari kamis, yaitu setelah shalat Zuhur sebanayak 100 kali, tanpa berbicara dengan siapapun, dengan seizin Allah, keinginannya akan dikabulkan Allah."));
        list.add(new AsmaulHusnaModel("27", "البصير", "Al Bashiir", "Yang Maha Melihat","Allah itu Al-Bashir, artinya adalah Allah itu Maha Melihat segala sesuatu. Kita sebagai manusia hanya memiliki penglihatan yang terbatas.\nOrang yang membaca Yaa Bashiir sebanyak 100 kali setelah sholat jumat secara istiqamah, Allah WT akan mengaruniakan kepadanya penglihatan (mata) yang tajam dan cahaya dalam hatinya. Insya Allah. Jika suatu pekerjaan tidak diniatkan untuk diri sendiri melainkan karena Allah, kemudian orang tersebut membaca yaa Allaah yaa Bashiir sebanyak 100 kali sebelum sholat jumat, niscaya Allah akan menggembirakan orang itu dengan kasih sayang-Nya dan memberikannya keberhasilan dalam pekerjaan yang diniatkannya itu.","Barangsiapa mengamalkan Yaa Bashiir sebanyak 100 kali, yaitu antara shalat jum`at dan shalat sunah setelahnya, maka Allah akan meninggikan kedudukannya di mata orang lain."));
        list.add(new AsmaulHusnaModel("28", "الحكم,", "Al Hakam", "Yang Maha Menetapkan","Maha Menghukum / Maha Mengadili, yaitu sebagai hakim yang menetapkan / memutuskan yang tidak seorang pun dapat menolak keputusanNya, juga tidak seorang pun yang berkuasa merintangi kelangsungan hukumNya itu.","Barangsiapa membaca Yaa Hakam berulang kali pada malam hari, maka dengan izin-Nya, rahasia (hal-hal yang tersembunyi) akan dinampakkan padanya."));
        list.add(new AsmaulHusnaModel("29", "العدل", "Al `Adl", "Yang Maha Adil","Maha Adil. Serta sangat sempurna dalam keadilanNya itu.","Bila seseorang menuliskan bacaan Yaa`Adl di atas sekerat roti pada malam jum`at lalu memakan roti itu, maka dengan izin Allah, orang lain akan menuruti ucapannya."));
        list.add(new AsmaulHusnaModel("30", "اللطيف", "Al Lathiif", "Yang Maha Lembut","Maha Menghalusi / Maha Teliti / Maha Lembut serta Halus, yaitu mengetahui segala sesuatu yang samar-samar, pelik-pelik dan kecil-kecil.","Bacaan Yaa Lathiif memiliki beberapa faedah. Yaitu bisa mendekatkan kita pada hasil, menghilangkan semua rasa sakit, penyakit, dan semua kesulitan. Di saat ada bencana, kesusahan, dan kesedihan, melafalkannya dapat mendatangkan keselamatan, kebahagiaan, keamanan, dan keyakinan."));
        list.add(new AsmaulHusnaModel("31", "الخبير", "Al Khabiir", "Yang Maha Mengenal","Maha Waspada / Maha Mengetahui.","Seseorang yang memiliki kebiasaan buruk lalu ia membaca Yaa Khobiir berkali-kali, maka dengan seizin Allah, kebiasaan buruknya itu akan segera menghilang dari dirinya."));
        list.add(new AsmaulHusnaModel("32", "الحليم", "Al Haliim", "Yang Maha Penyantun","Maha Penyabar / Maha Penyantun / Maha Penghamba, yaitu yang tidak tergesa-gesa melakukan kemarahan dan tidak pula gelojoh memberikan siksaan.","Dianjurkan untuk rutin membaca Yaa Haliim 100 kali dalam sehari untuk meredakan kemarahan dan mengetahui hal-hal yang ghaib, untuk memadamkan api kemarahan dan kebodohan, serta untuk mendapatkan ketenangan hati dan terjaga dari berbagai bencana."));
        list.add(new AsmaulHusnaModel("33", "العظيم", "Al `Azhiim", "Allah Yang Maha Agung","Maha Agung, yaitu mencapai puncak tertinggi dan di mercu keagungan kerana bersifat dengan segala macam sifat kebesaran dan kesempunnaan.","Orang yang sering mengamalkan bacaan Yaa `Azhiim, dengan seizin Allah, akan dihormati oleh orang lain."));
        list.add(new AsmaulHusnaModel("34", "الغفور", "Al Ghafuur", "Allah Yang Maha Memberi Pengampunan","Maha Pengampun, banyak pengampunanNya kepada hamba-hambaNya.","Orang yang terserang sakit kepala dan demam lalu ia membaca Yaa Ghofuur, maka dengan siizin Allah, ia akan sembuh dari penyakit yang dideritanya itu. Banyak mengulang-ulang asma ini juga dapat menghilangkan penyakit was-was."));
        list.add(new AsmaulHusnaModel("35", "الشكور", "As Syakuur", "Allah Yang Maha Pembalas Budi (Menghargai)","Maha Pembalas / Maha Bersyukur, yaitu memberikan balasan yang banyak sekali atas amalan yang kecil.","Barangsiapa yang bersedih lalu ia membaca Yaa Syaakuur sebanyak 41 kali kemudian meniupkannya ke dalam segelas air dan membasuh wajahnya dengan air tersebut. Maka dengan siizin Allah, hatinya akan menjadi tentram dan tenang. Dan ia akan dapat mencukupi kebutuhannya."));
        list.add(new AsmaulHusnaModel("36", "العلى", "Al `Aliy", "Allah Yang Maha Tinggi","Maha Tinggi Martabat-Nya / Maha Tinggi serta Mulia, yaitu mencapai tingkat yang setinggi-tingginya yang tidak mungkin digambarkan oleh akal fikiran sesiapa pun dan tidak dapat difahami oleh otak yang bagaimanapun pandainya.","Barangsiapa kadar imannya sedang turun lalu ia membaca Yaa `Aliyy berkali-kali, maka dengan siizin Allah, imannya akan kembali meningkat serta peruntungannya terbuka. Dan bagi seseorang yang tengah dalam perjalanan pulang, dengan seizin Allah, ia akan sampai ke kampung halamannya dengan selamat."));
        list.add(new AsmaulHusnaModel("37", "الكبير", "Al Kabiir", "Yang Maha Besar","Maha Besar, yang kebesaranNya tidak dapat dicapai oleh pancaindera ataupun akal manusia.","Barangsiapa ingin mendapatkan penghormatan maka bacalah Yaa Kabiir seratus kali setiap hari."));
        list.add(new AsmaulHusnaModel("38", "الحفيظ", "Al Hafizh", "Allah Yang Maha Memelihara","Maha Pemelihara Maha Pelindung / Maha Memelihara, yaitu menjaga segala sesuatu jangan sampai rosak dan goyah. Juga menjaga segala amal perbuatan hamba-hambaNya, sehingga tidak akan disia-siakan sedikit pun untuk memberikan balasanNya.","Orang yang membaca Yaa Haafiizh enam belas kali setiap hari, dengan siizin Allah, ia akan terlindung dari berbagai musibah. Jika dibaca 998 kali, ia akan terlindung dari segala macam ketakutan meski ia pergi ke tempat berbahaya. Ia juga terjaga dari bahaya tenggelam. Ucapannya akan selalu terjaga dan doanya akan cepat terjawab."));
        list.add(new AsmaulHusnaModel("39", "المقيت", "Al Muqiit", "Allah Yang Maha Pemberi Kecukupan","Maha Pemberi Kecukupan / Maha Pemberi Keperluan, baik yang berupa makanan tubuh ataupun makanan rohani.","Apabila seseorang mempunyai anak dengan perangai buruk, hendaknya ia membaca Yaa Muqiit berulang-ulang lalu ditiupkan ke dalam segelas air dan meminumkannya kepada anak tersebut. Maka dengan seizin allah, anak tersebut akan berperangai baik."));
        list.add(new AsmaulHusnaModel("40", "الحسيب", "Al Hasiib", "Allah Yang Maha Membuat Perhitungan","Maha Penjamin / Maha Mencukupi / Maha Penghitung, yaitu memberikan jaminan kecukupan kepada seluruh bamba-hambaNya pada hari Kiamat.","Jika seseorang takut dirampok, didengki, diganggu, atau dizalimi oleh orang lain, hendaknya mulai hari kamis ia membaca Yaa Hasiib sebanyak 70 kali siang dan malam selama tujuh hari. Dan pada hitungan ke-71 ia mengucapkan Hasbiyallaahul-Hasiib. Insya Allah, rasa takut yang ada di dalam dirinya itu akan lenyap."));
        list.add(new AsmaulHusnaModel("41", "الجليل", "Al Jaliil", "Allah Yang Maha Luhur","Maha Luhur, yaitu yang memiliki sifat-sifat keluhuran kerana kesempurnaan sifat-sifatNya.","Perbanyaklah membaca Yaa Jaliil untuk menambah amalan pahala kebaikan."));
        list.add(new AsmaulHusnaModel("42", "الكريم", "Al Kariim", "Allah Yang Maha Pemurah","Maha Pemurah, yaitu mulia tanpa had dan memberi siapa pun tanpa diminta atau sebagai penggantian dan sesuatu pemberian.","Orang yang mengamalkan bacaan Yaa Kariim, dengan seizin Allah, ia akan mendapatkan kemuliaan baik di dunia maupun di akhirat kelak."));
        list.add(new AsmaulHusnaModel("43", "الرقيب", "Ar Raqiib", "Allah Yang Maha Mengawasi","Maha Peneliti / Maha Pengawas Maha Waspada, yaitu yang mengamat-amati gerak-geri segala sesuatu dan mengawasinya.","Barangsiapa membaca Yaa Raqiib sebanyak tujuh kali untuk dirinya sendiri, keluarga, dan kekayaannya, dengan seizin Allah, semuanya itu akan berada di bawah perlindungan Allah. Jika bacaan ini senantiasa diamalkan maka kelalaian akan sirna dari hati."));
        list.add(new AsmaulHusnaModel("44", "المجيب", "Al Mujiib", "Allah Yang Maha Mengabulkan","Maha Mengabulkan, yaitu yang memenuhi permohonan siapa saja yang berdoa padaNya.","Permohonan seorang hamba yang disertai dengan penyebutan Yaa Mujiib, Insya Allah, akan dikabulkan oleh Allah."));
        list.add(new AsmaulHusnaModel("45", "الواسع", "Al Waasi`", "Allah Yang Maha Luas","Maha Luas Pemberian-Nya , yaitu kerahmatanNya merata kepada segala yang maujud dan luas pula ilmuNya terhadap segala sesuatu.","Barangsiapa sulit mendapatkan nafkah lalu membaca Yaa Waasi`, dengan seizin Allah, ia akan mendapatkan sumber nafkah yang layak."));
        list.add(new AsmaulHusnaModel("46", "الحكيم", "Al Hakim", "Allah Yang Maha Bijaksana","Maha Bijaksana, yaitu memiliki kebijaksanaan yang tertinggi kesempurnaan ilmuNya serta kerapiannya dalam membuat segala sesuatu.","Seseorang yang rajin membaca Yaa Hakiim dari waktu ke waktu, dengan seizin Allah, ia tidak akan mendapatkan kesulitan dalam pekerjaannya."));
        list.add(new AsmaulHusnaModel("47", "الودود", "Al Waduud", "Allah Yang Maha Mengasihi","Maha Pencinta / Maha Menyayangi, yaitu yang menginginkan segala kebaikan untuk seluruh hambaNya dan juga berbuat baik pada mereka itu dalam segala hal dan keadaan.","Bila terjadi persengketaan di antara dua orang, kemudian salah satunya membaca Yaa Waduud seribu kali pada makanan atau minuman lalu meminta orang yang bersengketa dengannya mengkonsumsi makanan atau minuman tersebut, dengan seizin Allah, persengketaan mereka berdua akan selesai."));
        list.add(new AsmaulHusnaModel("48", "المجيد", "Al Majiid", "Allah Yang Maha Mulia","Maha Mulia, yaitu yang mencapai tingkat teratas dalam hal kemuliaan dan keutamaan.","Orang yang sering membaca Yaa Majiid, dengan seizin allah, ia akan dianugerahi kemuliaan oleh Allah SWT."));
        list.add(new AsmaulHusnaModel("49", "الباعث", "Al Baa`its", "Allah Yang Maha Membangkitkan","Maha Membangkitkan, yaitu membangkitkan semangat dan kemahuan, juga membangkitkan para Rasul dan orang-orang yang telah mati dari kubur masing-masing nanti setelah tibanya hari Qiamat.","Membaca Yaa Baa`its berulang-ulang akan mendatangkan rasa takut kita kepada Allah SWT. Seseorang yang sebelum tidur mengusapkan tangannya ke dada dan melafalkan bacaan ini seratus kali, Allah SWT akan menghidupkan hatinya dengan cahaya makrifat-Nya."));
        list.add(new AsmaulHusnaModel("50", "الشهيد", "As Syahiid", "Allah Yang Maha Menyaksikan","Maha Menyaksikan / Maha Mengetahui keadaan semua makhluk.","Orangtua yang mempunyai anak yang nakal dianjurkan untuk membaca Yaa Syahiid berulang-ulang untuk anaknya tersebut. Insya Allah, Allah akan memberikan kesalihan kepada anak itu."));
        list.add(new AsmaulHusnaModel("51", "الحق", "Al Haqq", "Allah Yang Maha Benar","Maha Haq / Maha Benar yang kekal dan tidak akan berubah sedikit pun.","Apabila seseorang kehilangan sesuatu lalu membaca Yaa Haqq berulang-ulang, dengan seizin Allah, ia akan menemukan sesuatu yang hilang tersebut."));
        list.add(new AsmaulHusnaModel("52", "الوكيل", "Al Wakiil", "Allah Yang Maha Memelihara","Maha Pentadbir / Maha Berserah / Maha Memelihara penyerahan, yakni memelihara semua urusan hamba-hambaNya dan apa-apa yang menjadi keperluan mereka itu.","Orang yang takut tenggelam, terbakar api, atau bahaya lain yang sejenis, hendaknya sering mengulang-ulang membaca Yaa Wakiil. Dengan seizin Allah, ia akan selalu berada dalam lindungan Allah SWT. Bacaan ini juga memiliki pengaruh yang luar biasa untuk mendekatkan kita pada apa yang diinginkan dan juga untuk memenuhi kebutuhan kita. "));
        list.add(new AsmaulHusnaModel("53", "القوى", "Al Qawiyyu", "Allah Yang Maha Kuat","Maha Kuat / Maha Memiliki Kekuatan , yaitu yang memiliki kekuasaan yang sesempurnanya.","Seseorang yang tidak mampu mengalahkan musuhnya lalu mengucapkan Yaa Qowiyy dengan tujuan agar tidak dizalimi, dengan seizin Allah, ia akan terbebas dari gangguan musuhnya itu."));
        list.add(new AsmaulHusnaModel("54", "المتين", "Al Matiin", "Allah Yang Maha Kokoh","Maha Teguh / Maha Kukuh atau Perkasa / Maha Sempurna Kekuatan-Nya , yaitu memiliki keperkasaan yang sudah sampai di puncaknya.","Barangsiapa yang sedang tertimpa suatu kesulitan lalu melafalkan Yaa Matiin berulang-ulang, dengan seizin Allah, kesulitannya akan sirna. "));
        list.add(new AsmaulHusnaModel("55", "الولى", "Al Waliyy", "Allah Yang Maha Melindungi","Maha Melindungi, yaitu melindungi serta mengaturkan semua kepentingan makhlukNya kerana kecintaanNya yang amat sangat dan pemberian pertolonganNya yang tidak terbatas pada keperluan mereka.","Barangsiapa sering mengamalkan Yaa Waliyy, dengan seizin Allah, ia akan menjadi kekasih atau wali Allah. "));
        list.add(new AsmaulHusnaModel("56", "الحميد", "Al Hamiid", "Allah Yang Maha Terpuji","Maha Terpuji, yang memang sudah selayaknya untuk memperoleh pujian dan sanjungan.","Orang yang sering mengucapkan Yaa Hamiid, dengan seizin Allah, ia akan dicintai dan dihormati oleh orang lain."));
        list.add(new AsmaulHusnaModel("57", "المحصى", "Al Muhshii", "Allah Yang Maha Mengalkulasi (Menghitung Segala Sesuatu)","Maha Menghitung / Maha Penghitung, yaitu yang tiada satu pun tertutup dari pandanganNya dan semua amalan diperhitungkan sebagaimana wajarnya.","Bila seseorang takut tidak bisa menjawab pertanyaan pada hari pengadilan di akhirat kelak, hendaknya ia sering membaca Yaa Muhshii sebanyak seribu kali. Insya Allah, ia akan mendapat kemudahan."));
        list.add(new AsmaulHusnaModel("58", "المبدئ", "Al Mubdi`", "Allah Yang Maha Memulai","Maha Memulai/Pemula / Maha Pencipta dari Asal, yaitu yang melahirkan sesuatu yang asalnya tidak ada dan belum maujud.","Sekiranya Yaa Mubdi` dibaca berulang-ulang lalu ditiupkan kepada wanita yang hamil yang takut keguguran, Insya Allah, ia tidak akan mengalami musibah itu."));
        list.add(new AsmaulHusnaModel("59", "المعيد", "Al Mu`iid", "Allah Yang Maha Mengembalikan Kehidupan","Maha Mengulangi / Maha Mengembalikan dan Memulihkan, yaitu menumbuhkan kembali setelah lenyapnya atau setelah rosaknya.","Jika Yaa Mu`iid dibaca sebanyak tujuh puluh kali dan ditujukan kepada seeorang yang jauh dari keluarganya, dengan seizin Allah, orang tersebut akan pulang dengan selamat. "));
        list.add(new AsmaulHusnaModel("60", "المحيى", "Al Muhyii", "Allah Yang Maha Menghidupkan","Maha Menghidupkan, yaitu memberikan daya kehidupan pada setiap sesuatu yang berhak hidup.","Bila seseorang sedang memikul beban persoalan yang berat lalu ia mengucakan Yaa Muhyii tujuh kali setiap hari, Insya Allah, beban tersebut akan terlepas darinya. "));
        list.add(new AsmaulHusnaModel("61", "المميت", "Al Mumiitu", "Allah Yang Maha Mematikan","Maha Mematikan, yaitu mengambil kehidupan (roh) dari apa-apa yang hidup.","Bacaan Yaa Mumiit memiliki manfaat besar untuk menghancurkan dan mematahkan kekuatan musuh."));
        list.add(new AsmaulHusnaModel("62", "الحي", "Al Hayyu", "Allah Yang Maha Hidup","Maha Hidup, yaitu sentiasa kekal hidupNya itu.","Bacaan Yaa Hayy berkhasiat memanjangkan umur. Baragsiapa yang rutin membacanya, khususnya setiap setelah selesai shalat sebanyak 18 kali, Insya Allah, ia akan terhindar dari kematian mendadak dan rejekinya diluaskan. Untuk mengobati sakit mata, bacalah Yaa Hayy sembilan belas kali. Insya Allah akan sembuh."));
        list.add(new AsmaulHusnaModel("63", "القيوم", "Al Qayyuum", "Allah Yang Maha Mandiri","Maha Berdiri Dengan Sendiri-Nya , yaitu baik ZatNya, SifatNya, Af`alNya. Juga membuat berdirinya apa-apa yang selain Dia. DenganNya pula berdirinya langit dan bumi ini.",""));
        list.add(new AsmaulHusnaModel("64", "الواجد", "Al Waajid", "Allah Yang Maha Penemu","Maha Penemu / Maha Menemukan, yaitu dapat menemukan apa saja yang diinginkan olehNya, maka tidak berkehendakkan pada suatu apa pun kerana sifat kayaNya yang secara mutlak.","Seseorang yang ingin jadi pemurah hendaknya memperbanyak mambaca Yaa Waajid."));
        list.add(new AsmaulHusnaModel("65", "الماجد", "Al Maajid", "Allah Yang Maha Mulia","Maha Mulia, (sama dengan no. 48 yang berbeda hanyalah tulisannya dalam bahasa Arab, Ejaan sebenarnya no. 48 Al-Majiid, sedang no. 65 A1-Maajid).","Orang yang sering mengamalkan Yaa Maajid, dengan seizin Allah, hatinya akan tercerahkan. "));
        list.add(new AsmaulHusnaModel("66", "الواحد", "Al Wahid", "Allah Yang Maha Tunggal","Maha Esa.","Orang yang membaca Yaa Waahid berulang-ulang dalam kondisi yang menyendiri dan di tempat yang tenang, dengan seizin Allah dia akan terlepas dari rasa takut dan angan-angan. Bacaan ini juga berpengaruh besar dalam mendatangkan kasih sayang. Juga kedekatan serta kemuliaan di antara keluarga dan sanak keluarga dan sanak saudara. "));
        list.add(new AsmaulHusnaModel("67", "الاحد", "Al Ahad", "Allah Yang Maha Esa","Maha Tunggal.","Orang yang membaca Yaa Ahad seribu kali, dengan seizin Allah, sejumlah rahasia tertentu akan disingkap baginya. Barangsiapa yang tengah sendiri setelah menahan nafsu atau memperbanyak ibadah kemudian mengucapkan Yaa Ahad seribu kali, Insya Allah, ia akan menyaksikan malaikat di sekitarnya."));
        list.add(new AsmaulHusnaModel("68", "الصمد", "As Shamad", "Allah Yang Maha Dibutuhkan, Tempat Meminta","Maha Diperlukan / Maha Diminta / Yang Menjadi Tumpuan, yaitu selalu menjadi tujuan dan harapan orang di waktu ada hajat keperluan.","Barangsiapa rajin membaca Yaa Shomad berulang-ulang, Insya Allah, Allah akan memenuhi kebutuhannya."));
        list.add(new AsmaulHusnaModel("69", "القادر", "Al Qaadir", "Allah Yang Maha Menentukan, Maha Menyeimbangkan","Maha Berkuasa / Maha Kuasa / Maha Berupaya.","Barangsiapa sering mengamalkan Yaa Qoodir, dengan seizin Allah, semua hasrat dan keinginannya akan terkabul."));
        list.add(new AsmaulHusnaModel("70", "المقتدر", "Al Muqtadir", "Allah Yang Maha Berkuasa","Maha Menentukan, Maha Menyeimbangkan.","Orang yang membaca Yaa Muqtadir terus menerus, dengan seizin Allah, ia akan memiliki pengetahuan tentang kebenaran."));
        list.add(new AsmaulHusnaModel("71", "المقدم", "Al Muqaddim", "Allah Yang Maha Mendahulukan","Maha Mendahulukan / Maha Menyegera, yaitu mendahulukan sebahagian benda dari yang lainnya dalam mewujudnya, atau dalam kemuliaannya, selisih waktu atau tempatnya.","Seseorang yang membaca Yaa Muqoddim berkali-kali di medan peperangan atau di suatu tempat yang menakutkan, Insya Allah, ia tidak akan terkena gangguan. "));
        list.add(new AsmaulHusnaModel("72", "المؤخر", "Al Mu`akkhir", "Allah Yang Maha Mengakhirkan","Maha Menangguhkan / Maha Mengakhirkan / Maha Membelakangkan / Maha Melambat-lambatkan. Yaitu melewatkan sebahagian sesuatu dari yang lainnya.","Barangsiapa membaca Yaa Muakhkhir di dalam hati sebanyak seratus kali setiap hari, Insya Allah, relung hatinya akan dipenuhi dengan kecintaan kepada Allah. Tidak ada kecintaan kepada selain-Nya."));
        list.add(new AsmaulHusnaModel("73", "الأول", "Al Awwal", "Allah Yang Maha Awal","Maha Pemulaan / Maha Pertama, yaitu terdahulu sekali dari semua yang maujud.","Barangsiapa ingin dikaruniaiseorang anak, atau ingin bertemu dengan seseorang yang sedang berpergian jauh maka bacalah Yaa Awwal sebanyak seribu kali selama empat puluh jum`at."));
        list.add(new AsmaulHusnaModel("74", "الأخر", "Al Aakhir", "Allah Yang Maha Akhir","Maha Penghabisan / Yang Akhir, yaitu kekal terus setelah habisnya segala sesuatu yang maujud","Seseorang yang sering membaca Yaa Aakhir akan menjalani hidup dengan baik. Dan di akhir hayatnya, Insya Allah, ia akan menutup usianya dengan baik. "));
        list.add(new AsmaulHusnaModel("75", "الظاهر", "Az Zhaahir", "Allah Yang Maha Nyata","Maha Zahir / Maha Nyata / Maha Menyatakan, yaitu menyatakan dan menampakkan kewujudanNya itu dengan bukti-bukti dan tanda-tanda ciptaanNya.","Barangsiapa membaca Yaa Zhaahir sebanyak lima belas kali setelah shalat jum`at, dengan seizin Allah, cahaya Ilahi akan masuk ke hatinya."));
        list.add(new AsmaulHusnaModel("76", "الباطن", "Al Baathin", "Allah Yang Maha Ghaib","Maha Tersembunyi, yaitu tidak dapat dimaklumi ZatNya, sehingga tidak seorang pun dapat mengenal ZatNya itu.","Barangsiapa ingin melihat kebenaran dalam berbagai hal, bacalah Yaa Baathin tiga kali setiap hari. "));
        list.add(new AsmaulHusnaModel("77", "الوالي", "Al Waali", "Allah Yang Maha Memerintah","Maha Menguasai / Maha Menguasai Urusan / Yang Maha Memerintah, yaitu menggenggam segala sesuatu dalam kekuasaanNya dan menjadi milikNya.","Bila seseorang membaca Yaa Waalii berulang-ulang lalu meniupkannya ke dalam rumahnya, maka dengan seizin Allah, Allah akan melindungi rumah tersebut dari bahaya."));
        list.add(new AsmaulHusnaModel("78", "المتعالي", "Al Muta`aalii", "Allah Yang Maha Tinggi","Maha Suci/Tinggi, yaitu terpelihara dari segala kekurangan dan kerendahan.","Bila seseorang rajin membaca Yaa Muta`aalii berulang-ulang, dengan seizin Allah, Allah akan memberinya banyak kebaikan."));
        list.add(new AsmaulHusnaModel("79", "البر", "Al Barru", "Allah Yang Maha Penderma (Maha Pemberi Kebajikan)","Maha Dermawan / Maha Bagus (Sumber Segala Kelebihan) / Yang banyak membuat kebajikan, yaitu banyak kebaikanNya dan besar kenikmatan yang dilimpahkanNya.","Bila seseorang rajin membaca Yaa Barr untuk anaknya, dengan seizin Allah, anaknya akan terlepas dari berbagai kemalangan."));
        list.add(new AsmaulHusnaModel("80", "التواب", "At Tawwaab", "Allah Yang Maha Penerima Tobat","Maha Penerima Taubat, yaitu memberikan pertolongan kepada orang-orang yang melakukan maksiat untuk bertaubat lalu Allah akan menerimanya.","Bila seseoarang rajin membaca Yaa Tawwaab berulang-ulang, dengan seizin Allah, Allah akan menerima tobatnya."));
        list.add(new AsmaulHusnaModel("81", "المنتقم", "Al Muntaqim", "Allah Yang Maha Pemberi Balasan","Maha Penyiksa / Yang Maha Menghukum, kepada mereka yang bersalah dan orang yang berhak untuk memperoleh siksaNya.","Bila seseorang rajin membaca Yaa Muntaqim berulang-ulang, dengan seizin Allah, Allah akan memberinya kemenangan bila ia berhadapan dengan musuh."));
        list.add(new AsmaulHusnaModel("82", "العفو", "Al Afuww", "Allah Yang Maha Pemaaf","Maha Pemaaf / Yang Maha Pengampun, menghapuskan kesalahan orang yang suka kembali untuk meminta maaf padaNya.","Bila seseorang rajin membaca Yaa Afuww berulang-ulang, dengan seizin Allah, Allah akan mengampuni dosa-dosanya."));
        list.add(new AsmaulHusnaModel("83", "الرؤوف", "Ar Ra`uuf", "Allah Yang Maha Pengasuh","Maha Pengasih / Maha Mengasihi, banyak kerahmatan dan kasih sayangNya.","Bila Seseorang rajin membaca Yaa Roo`uuf berulang-ulang, dengan seizin Allah, ia akan mendapatkan keberkahan dari Allah."));
        list.add(new AsmaulHusnaModel("84", "مالك الملك", "Malikul Mulk", "Allah Yang Maha Penguasa Kerajaan (Semesta)","Maha Pemilik Kekuasaan / Maha Menguasai kerajaan / Pemilik Kedaulatan Yang Kekal, maka segala perkara yang berlaku di alam semesta, langit, bumi dan sekitarnya serta yang di alam semesta itu semuanya sesuai dengan kehendak dan iradatNya.","Bila seseorang rajin membaca Yaa Maalikul-Mulk berulang-ulang, dengan seizin Allah, Allah akan memberi martabat dan harga diri kepadanya di mata manusia."));
        list.add(new AsmaulHusnaModel("85", "ذو الجلال و الإكرام", "Dzul Jalaali Wal Ikraam", "Allah Yang Maha Pemilik Kebesaran dan Kemuliaan","Maha Pemilik Keagungan dan Kemuliaan / Maha Memiliki Kebesaran dan Kemuliaan. Juga Zat yang mempunyai keutamaan dan kesempurnaan, pemberi kurnia dan kenikmatan yang amat banyak dan melimpah ruah.","Bila seseorang rajin membaca Yaa Dzul-Jalaali-Wal-Ikroom, dengan seizin Allah, Allah akan memberinya kekayaan."));
        list.add(new AsmaulHusnaModel("86", "المقسط", "Al Muqsith", "Allah Yang Maha Pemberi Keadilan","Maha Mengadili / Maha Saksama, yaitu memberikan kemenangan pada orang-orang yang teraniaya dari tindakan orang-orang yang menganiaya dengan keadilanNya.","Bila seseorang rajin membaca Yaa Muqsith berulang-ulang, dengan seizin Allah, Allah akan melindunginya dari gangguan setan."));
        list.add(new AsmaulHusnaModel("87", "الجامع", "Al Jamii`", "Allah Yang Maha Mengumpulkan","Maha Mengumpulkan / Maha Pengumpul, yaitu mengumpulkan berbagai hakikat yang telah bercerai-berai dan juga mengumpulkan seluruh umat manusia pada hari pembalasan.","Bila seseorang kehilangan sesuatu, ia bisa membaca Yaa jaami` berulang-ulang. Allah akan membantu mempermudah pencarian barangnya yang hilang itu. "));
        list.add(new AsmaulHusnaModel("88", "الغنى", "Al Ghaniyy", "Allah Yang Maha Kaya","Maha Kaya Raya / Maha Kaya serta Serba Lengkap, yaitu tidak berkehendakkan apa juapun dari yang selain ZatNya sendiri, tetapi yang selainNya itu amat mengharapkan padaNya.","Bila seseorang rajin membaca Yaa Ghaniyy, dengan seizin Allah, Allah akan memberinya perasaan cukup dengan apa yang dimiliki dan tidak akan dijangkiti sifat serakah. "));
        list.add(new AsmaulHusnaModel("89", "المغنى", "Al Mughnii", "Allah Yang Maha Pemberi Kekayaan","Maha Pemberi kekayaan / Maha Mengkayakan dan Memakmurkan, yaitu memberikan kelebihan yang berupa kekayaan yang berlimpah-ruah kepada siapa saja yang dikehendaki dari golongan hamba-hambaNya.","Bila seseorang rajin membaca Yaa Mughnii sebanyak sepuluh kali selama sepuluh jumat, dengan seizin Allah, Allah akan mencukupi kebutuhannya. "));
        list.add(new AsmaulHusnaModel("90", "المانع", "Al Maani", "Allah Yang Maha Mencegah","Maha Membela atau Maha Menolak / Maha Pencegah, yaitu membela hamba-hambaNya yang soleh dan menolak sebab-sebab yang menyebabkan kerosakan.","Bagi orang yang sudah berumah tangga, bila rajin membaca Yaa Maani`, dengan seizin Allah, Allah akan memberi ketenteraman hidup dalam rumah tangganya."));
        list.add(new AsmaulHusnaModel("91", "الضار", "Ad Dhaar", "Allah Yang Maha Penimpa Kemudharatan","Maha Mendatangkan Mudharat / Maha Pembuat Bahaya / Maha Pemberi bahaya, yaitu dengan menurunkan seksa-seksaNya kepada musuh-musuhNya.","Bila seseorang rajin membaca Yaa Dhaar pada malam jum`at, dengan seizin Allah, Allah akan mengangkat derajat dan kedudukannya ke tempat yang lebih tinggi."));
        list.add(new AsmaulHusnaModel("92", "النافع", "An Nafii`", "Allah Yang Maha Memberi Manfaat","Maha Pemberi Manfaat, yaitu meluaslah kebaikan yang dikurniakanNya itu kepada semua hamba, masyarakat dan negeri.","Bila seseorang membaca Yaa Naafi` empat hari berturut-turut, maka dengan seizin Allah, ia bakal terhindar dari banyak gangguan."));
        list.add(new AsmaulHusnaModel("93", "النور", "An Nuur", "Allah Yang Maha Bercahaya (Menerangi, Memberi Cahaya)","Maha Pemberi Cahaya / Maha Bercahaya, yaitu menonjokan ZatNya sendiri dan menampakkan untuk yang selainNya dengan menunjukkan tanda-tanda kekuasaanNya.","Bila Seseorang rajin membaca Yaa Nuur, maka dengan seizin Allah, Allah akan memberinya karunia cahaya batiniah. Dan Allah juga akan memberinya pengetahuan untuk mengetahui hal-hal yang tersembunyi. "));
        list.add(new AsmaulHusnaModel("94", "الهادئ", "Al Haadii", "Allah Yang Maha Pemberi Petunjuk","Maha Pemberi Petunjuk / Yang Memimpin dan Memberi Pertunjuk, yaitu memberikan jalan yang benar kepada segala sesuatu agar berterusan adanya dan terjaga kehidupannya.","Bila seseorang ingin memiliki pengetahuan spiritual dan makrifat atau ilmu mengenai Allah SWT. Maka perbanyaklah membaca Yaa Haadii."));
        list.add(new AsmaulHusnaModel("95", "البديع", "Al Badii’", "Allah Yang Maha Pencipta Yang Tiada Bandingannya","Maha Indah / Tiada Bandingan / Maha Pencipta yang baru, sehingga tidak ada contoh dan yang menyamai sebelum keluarnya ciptaanNya itu.","Bila seseorang membaca Yaa Badii`assamaawaati wal ardh (wahai Sang Pencipta segala sesuatu yang tiada banding di muka bumi dan jagat alam semesta) sebanyak tujuh puluh kali maka dengan seizin Allah, segala kesulitan yang menimpanya akan berakhir."));
        list.add(new AsmaulHusnaModel("96", "الباقي", "Al Baaqii", "Allah Yang Maha Kekal","Maha Kekal, yaitu kekal hidupNya untuk selama-lamanya.","Bila seseorang membaca Yaa Baaqii seratus kali sebelum matahari terbit maka, dengan seizin Allah, ia akan terbebas dari seluruh bencana di sepanjang hidupnya. Dan di akhirat kelak, ia akan dikasihi oleh Allah SWT. "));
        list.add(new AsmaulHusnaModel("97", "الوارث", "Al Waarits", "Allah Yang Maha Pewaris","Maha Membahagi / Maha Mewarisi / Maha Pewaris, yaitu kekal setelah musnahnya seluruh makhluk.","Bila seseorang sering membaca Yaa Waarits maka Allah akan memperpanjang usianya. "));
        list.add(new AsmaulHusnaModel("98", "الرشيد", "Ar Rasyiid", "Allah Yang Maha Pandai","Maha Cendekiawan / Maha Pandai / Bijaksana / Maha Memimpin, yaitu yang memimpin kepada kebenaran, yaitu memberi penerangan dan panduan pada seluruh hambaNya dan segala peraturanNya itu berjalan mengikut ketentuan yang digariskan oleh kebijaksanaan dan kecendekiawanNya.","Bila seseorang membaca Yaa Rosyiid sebanyak seribu kali, yaitu diantara waktu shalat Maghrib dan shalat Isya, dengan seizin Allah, berbagai persoalannya akan terselesaikan."));
        list.add(new AsmaulHusnaModel("99", "الصبور", "As Shabuur", "Allah Yang Maha Sabar","Maha Penyabar yang tidak tergesa-gesa memberikan seksaan dan tidak juga cepat melaksanakan sesuatu sebelum masanya.","Ketika seseorang dalam kesulitan atau berduka, bacalah Yaa Shobuur sebanyak tiga ribu kali, dengan izin Allah, Allah akan memberinya jalan keluar. Jika Yaa Shobuur dibaca sebanyak seribu kali, Allah akan memberinya ilham berupa kesabaran atas segala kesusahan dan bala bencana yang menimpanya."));

        setRecyclerView(bind.recyclerViewAsmaulHusna, new AsmaulHusnaAdapter(list));
    }

    @Override
    protected View getContentView() {
        return bind.getRoot();
    }
}